package net.minecraft.client.addon.lavamobs.modelblock;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBlockGuardRaid extends ModelBase
{
    ModelRenderer body;
    ModelRenderer body1;
    ModelRenderer body2;
    ModelRenderer leftlegf;
    ModelRenderer leftlegf1;
    ModelRenderer leftlegf2;
    ModelRenderer leftlegf3;
    ModelRenderer leftlegf4;
    ModelRenderer leftlegf5;
    ModelRenderer leftlegf6;
    ModelRenderer leftleg;
    ModelRenderer leftleg1;
    ModelRenderer leftleg2;
    ModelRenderer leftleg3;
    ModelRenderer leftleg4;
    ModelRenderer leftleg5;
    ModelRenderer rightlegf;
    ModelRenderer rightlegf1;
    ModelRenderer rightlegf2;
    ModelRenderer rightlegf3;
    ModelRenderer rightlegf4;
    ModelRenderer rightlegf5;
    ModelRenderer rightlegf6;
    ModelRenderer rightleg;
    ModelRenderer rightleg1;
    ModelRenderer rightleg2;
    ModelRenderer rightleg3;
    ModelRenderer rightleg4;
    ModelRenderer rightleg5;
    ModelRenderer head;
    ModelRenderer head1;
    ModelRenderer head2;
    ModelRenderer head3;
    ModelRenderer head4;
    ModelRenderer head5;
    ModelRenderer head6;
    ModelRenderer head7;
    ModelRenderer head8;
    ModelRenderer head9;
    ModelRenderer head10;
    ModelRenderer head11;

    public ModelBlockGuardRaid()
    {
        super.textureWidth = 32;
        super.textureHeight = 32;
        this.body = new ModelRenderer(this, 0, 0);
        this.body.addBox(-2.5F, 12.0F, -5.0F, 5, 4, 3);
        this.body.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.body.setTextureSize(32, 32);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0F, 0.0F, 0.0F);
        this.body1 = new ModelRenderer(this, 0, 0);
        this.body1.addBox(-2.5F, 11.0F, 7.0F, 5, 6, 7);
        this.body1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.body1.setTextureSize(32, 32);
        this.body1.mirror = true;
        this.setRotation(this.body1, -0.3490659F, 0.0F, 0.0F);
        this.body.addChild(this.body1);
        this.body2 = new ModelRenderer(this, 0, 0);
        this.body2.addBox(-3.5F, 11.0F, -1.0F, 7, 7, 7);
        this.body2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.body2.setTextureSize(32, 32);
        this.body2.mirror = true;
        this.setRotation(this.body2, -0.2094395F, 0.0F, 0.0F);
        this.body.addChild(this.body2);
        this.leftlegf = new ModelRenderer(this, 0, 0);
        this.leftlegf.addBox(0.0F, -2.0F, -2.5F, 2, 5, 5);
        this.leftlegf.setRotationPoint(3.0F, 15.0F, 0.0F);
        this.leftlegf.setTextureSize(32, 32);
        this.leftlegf.mirror = true;
        this.setRotation(this.leftlegf, 0.0F, 0.0F, 0.0F);
        this.leftlegf1 = new ModelRenderer(this, 0, 0);
        this.leftlegf1.addBox(2.0F, -2.0F, -3.0F, 4, 6, 4);
        this.leftlegf1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegf1.setTextureSize(32, 32);
        this.leftlegf1.mirror = true;
        this.setRotation(this.leftlegf1, 0.4886922F, 0.0F, 0.0F);
        this.leftlegf.addChild(this.leftlegf1);
        this.leftlegf2 = new ModelRenderer(this, 3, 22);
        this.leftlegf2.addBox(1.5F, 6.0F, -6.0F, 5, 3, 7);
        this.leftlegf2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegf2.setTextureSize(32, 32);
        this.leftlegf2.mirror = true;
        this.setRotation(this.leftlegf2, 0.0F, 0.0F, 0.0F);
        this.leftlegf.addChild(this.leftlegf2);
        this.leftlegf3 = new ModelRenderer(this, 0, 0);
        this.leftlegf3.addBox(1.9F, 1.0F, 0.0F, 4, 6, 4);
        this.leftlegf3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegf3.setTextureSize(32, 32);
        this.leftlegf3.mirror = true;
        this.setRotation(this.leftlegf3, -0.5934119F, 0.0F, 0.0F);
        this.leftlegf.addChild(this.leftlegf3);
        this.leftlegf4 = new ModelRenderer(this, 22, 25);
        this.leftlegf4.addBox(5.0F, 6.5F, -7.0F, 1, 3, 1);
        this.leftlegf4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegf4.setTextureSize(32, 32);
        this.leftlegf4.mirror = true;
        this.setRotation(this.leftlegf4, 0.0F, 0.0F, 0.0F);
        this.leftlegf.addChild(this.leftlegf4);
        this.leftlegf5 = new ModelRenderer(this, 22, 25);
        this.leftlegf5.addBox(3.5F, 6.5F, -7.0F, 1, 3, 1);
        this.leftlegf5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegf5.setTextureSize(32, 32);
        this.leftlegf5.mirror = true;
        this.setRotation(this.leftlegf5, 0.0F, 0.0F, 0.0F);
        this.leftlegf.addChild(this.leftlegf5);
        this.leftlegf6 = new ModelRenderer(this, 22, 25);
        this.leftlegf6.addBox(2.0F, 6.5F, -7.0F, 1, 3, 1);
        this.leftlegf6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegf6.setTextureSize(32, 32);
        this.leftlegf6.mirror = true;
        this.setRotation(this.leftlegf6, 0.0F, 0.0F, 0.0F);
        this.leftlegf.addChild(this.leftlegf6);
        this.leftleg = new ModelRenderer(this, 0, 0);
        this.leftleg.addBox(0.0F, -2.0F, -2.0F, 3, 4, 4);
        this.leftleg.setRotationPoint(2.0F, 17.0F, 7.0F);
        this.leftleg.setTextureSize(32, 32);
        this.leftleg.mirror = true;
        this.setRotation(this.leftleg, -0.5061455F, 0.0F, 0.0F);
        this.leftleg1 = new ModelRenderer(this, 0, 0);
        this.leftleg1.addBox(3.0F, -1.0F, -1.0F, 3, 5, 3);
        this.leftleg1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftleg1.setTextureSize(32, 32);
        this.leftleg1.mirror = true;
        this.setRotation(this.leftleg1, 0.4537856F, 0.0F, 0.0F);
        this.leftleg.addChild(this.leftleg1);
        this.leftleg2 = new ModelRenderer(this, 0, 0);
        this.leftleg2.addBox(2.9F, 0.0F, 1.5F, 3, 4, 3);
        this.leftleg2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftleg2.setTextureSize(32, 32);
        this.leftleg2.mirror = true;
        this.setRotation(this.leftleg2, -0.6632251F, 0.0F, 0.0F);
        this.leftleg.addChild(this.leftleg2);
        this.leftleg3 = new ModelRenderer(this, 0, 24);
        this.leftleg3.addBox(3.0F, 4.0F, -3.0F, 3, 3, 5);
        this.leftleg3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftleg3.setTextureSize(32, 32);
        this.leftleg3.mirror = true;
        this.setRotation(this.leftleg3, 0.0F, 0.0F, 0.0F);
        this.leftleg.addChild(this.leftleg3);
        this.leftleg4 = new ModelRenderer(this, 22, 25);
        this.leftleg4.addBox(4.5F, 4.5F, -4.0F, 1, 3, 1);
        this.leftleg4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftleg4.setTextureSize(32, 32);
        this.leftleg4.mirror = true;
        this.setRotation(this.leftleg4, 0.0F, 0.0F, 0.0F);
        this.leftleg.addChild(this.leftleg4);
        this.leftleg5 = new ModelRenderer(this, 22, 25);
        this.leftleg5.addBox(3.0F, 4.5F, -4.0F, 1, 3, 1);
        this.leftleg5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftleg5.setTextureSize(32, 32);
        this.leftleg5.mirror = true;
        this.setRotation(this.leftleg5, 0.0F, 0.0F, 0.0F);
        this.leftleg.addChild(this.leftleg5);
        this.rightlegf = new ModelRenderer(this, 0, 0);
        this.rightlegf.addBox(-2.0F, -2.0F, -2.5F, 2, 5, 5);
        this.rightlegf.setRotationPoint(-3.0F, 15.0F, 0.0F);
        this.rightlegf.setTextureSize(32, 32);
        this.rightlegf.mirror = true;
        this.setRotation(this.rightlegf, 0.0F, 0.0F, 0.0F);
        this.rightlegf1 = new ModelRenderer(this, 0, 0);
        this.rightlegf1.addBox(-6.0F, -2.0F, -3.0F, 4, 6, 4);
        this.rightlegf1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegf1.setTextureSize(32, 32);
        this.rightlegf1.mirror = true;
        this.setRotation(this.rightlegf1, 0.4886922F, 0.0F, 0.0F);
        this.rightlegf.addChild(this.rightlegf1);
        this.rightlegf2 = new ModelRenderer(this, 0, 0);
        this.rightlegf2.addBox(-5.9F, 1.0F, 0.0F, 4, 6, 4);
        this.rightlegf2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegf2.setTextureSize(32, 32);
        this.rightlegf2.mirror = true;
        this.setRotation(this.rightlegf2, -0.5934119F, 0.0F, 0.0F);
        this.rightlegf.addChild(this.rightlegf2);
        this.rightlegf3 = new ModelRenderer(this, 3, 22);
        this.rightlegf3.addBox(-6.5F, 6.0F, -6.0F, 5, 3, 7);
        this.rightlegf3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegf3.setTextureSize(32, 32);
        this.rightlegf3.mirror = true;
        this.setRotation(this.rightlegf3, 0.0F, 0.0F, 0.0F);
        this.rightlegf.addChild(this.rightlegf3);
        this.rightlegf4 = new ModelRenderer(this, 22, 25);
        this.rightlegf4.addBox(-3.0F, 6.5F, -7.0F, 1, 3, 1);
        this.rightlegf4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegf4.setTextureSize(32, 32);
        this.rightlegf4.mirror = true;
        this.setRotation(this.rightlegf4, 0.0F, 0.0F, 0.0F);
        this.rightlegf.addChild(this.rightlegf4);
        this.rightlegf5 = new ModelRenderer(this, 22, 25);
        this.rightlegf5.addBox(-4.5F, 6.5F, -7.0F, 1, 3, 1);
        this.rightlegf5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegf5.setTextureSize(32, 32);
        this.rightlegf5.mirror = true;
        this.setRotation(this.rightlegf5, 0.0F, 0.0F, 0.0F);
        this.rightlegf.addChild(this.rightlegf5);
        this.rightlegf6 = new ModelRenderer(this, 22, 25);
        this.rightlegf6.addBox(-6.0F, 6.5F, -7.0F, 1, 3, 1);
        this.rightlegf6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegf6.setTextureSize(32, 32);
        this.rightlegf6.mirror = true;
        this.setRotation(this.rightlegf6, 0.0F, 0.0F, 0.0F);
        this.rightlegf.addChild(this.rightlegf6);
        this.rightleg = new ModelRenderer(this, 0, 0);
        this.rightleg.addBox(-3.0F, -2.0F, -2.0F, 3, 4, 4);
        this.rightleg.setRotationPoint(-2.0F, 17.0F, 7.0F);
        this.rightleg.setTextureSize(32, 32);
        this.rightleg.mirror = true;
        this.setRotation(this.rightleg, -0.5061455F, 0.0F, 0.0F);
        this.rightleg1 = new ModelRenderer(this, 0, 0);
        this.rightleg1.addBox(-6.0F, -1.0F, -1.0F, 3, 5, 3);
        this.rightleg1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightleg1.setTextureSize(32, 32);
        this.rightleg1.mirror = true;
        this.setRotation(this.rightleg1, 0.4537856F, 0.0F, 0.0F);
        this.rightleg.addChild(this.rightleg1);
        this.rightleg2 = new ModelRenderer(this, 0, 0);
        this.rightleg2.addBox(-5.9F, 0.0F, 1.5F, 3, 4, 3);
        this.rightleg2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightleg2.setTextureSize(32, 32);
        this.rightleg2.mirror = true;
        this.setRotation(this.rightleg2, -0.6632251F, 0.0F, 0.0F);
        this.rightleg.addChild(this.rightleg2);
        this.rightleg3 = new ModelRenderer(this, 0, 24);
        this.rightleg3.addBox(-6.0F, 4.0F, -3.0F, 3, 3, 5);
        this.rightleg3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightleg3.setTextureSize(32, 32);
        this.rightleg3.mirror = true;
        this.setRotation(this.rightleg3, 0.0F, 0.0F, 0.0F);
        this.rightleg.addChild(this.rightleg3);
        this.rightleg4 = new ModelRenderer(this, 22, 25);
        this.rightleg4.addBox(-5.5F, 4.5F, -4.0F, 1, 3, 1);
        this.rightleg4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightleg4.setTextureSize(32, 32);
        this.rightleg4.mirror = true;
        this.setRotation(this.rightleg4, 0.0F, 0.0F, 0.0F);
        this.rightleg.addChild(this.rightleg4);
        this.rightleg5 = new ModelRenderer(this, 22, 25);
        this.rightleg5.addBox(-4.0F, 4.5F, -4.0F, 1, 3, 1);
        this.rightleg5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightleg5.setTextureSize(32, 32);
        this.rightleg5.mirror = true;
        this.setRotation(this.rightleg5, 0.0F, 0.0F, 0.0F);
        this.rightleg.addChild(this.rightleg5);
        this.head = new ModelRenderer(this, 0, 0);
        this.head.addBox(-3.5F, -5.0F, -4.0F, 7, 8, 4);
        this.head.setRotationPoint(0.0F, 14.0F, -5.0F);
        this.head.setTextureSize(32, 32);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0F, 0.0F, 0.0F);
        this.head1 = new ModelRenderer(this, 0, 15);
        this.head1.addBox(-3.5F, 1.4F, -8.6F, 7, 2, 5);
        this.head1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head1.setTextureSize(32, 32);
        this.head1.mirror = true;
        this.setRotation(this.head1, -0.122173F, 0.0F, 0.0F);
        this.head.addChild(this.head1);
        this.head2 = new ModelRenderer(this, 0, 7);
        this.head2.addBox(-3.5F, -5.0F, -8.0F, 7, 4, 4);
        this.head2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head2.setTextureSize(32, 32);
        this.head2.mirror = true;
        this.setRotation(this.head2, 0.0F, 0.0F, 0.0F);
        this.head.addChild(this.head2);
        this.head3 = new ModelRenderer(this, 21, 22);
        this.head3.addBox(-1.0F, -2.0F, -9.0F, 2, 2, 1);
        this.head3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head3.setTextureSize(32, 32);
        this.head3.mirror = true;
        this.setRotation(this.head3, -0.1745329F, 0.0F, 0.0F);
        this.head.addChild(this.head3);
        this.head4 = new ModelRenderer(this, 26, 22);
        this.head4.addBox(-1.5F, -2.0F, -9.0F, 1, 2, 1);
        this.head4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head4.setTextureSize(32, 32);
        this.head4.mirror = true;
        this.setRotation(this.head4, 0.1919862F, 0.0F, 0.0F);
        this.head.addChild(this.head4);
        this.head5 = new ModelRenderer(this, 26, 22);
        this.head5.addBox(0.5F, -2.0F, -9.0F, 1, 2, 1);
        this.head5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head5.setTextureSize(32, 32);
        this.head5.mirror = true;
        this.setRotation(this.head5, 0.1919862F, 0.0F, 0.0F);
        this.head.addChild(this.head5);
        this.head6 = new ModelRenderer(this, 26, 22);
        this.head6.addBox(1.0F, -1.0F, -7.0F, 1, 1, 1);
        this.head6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head6.setTextureSize(32, 32);
        this.head6.mirror = true;
        this.setRotation(this.head6, 0.0F, 0.0F, -0.0872665F);
        this.head.addChild(this.head6);
        this.head7 = new ModelRenderer(this, 26, 22);
        this.head7.addBox(-2.0F, -1.0F, -7.0F, 1, 1, 1);
        this.head7.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head7.setTextureSize(32, 32);
        this.head7.mirror = true;
        this.setRotation(this.head7, 0.0F, 0.0F, 0.0872665F);
        this.head.addChild(this.head7);
        this.head8 = new ModelRenderer(this, 26, 22);
        this.head8.addBox(2.0F, -1.0F, -8.0F, 1, 2, 1);
        this.head8.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head8.setTextureSize(32, 32);
        this.head8.mirror = true;
        this.setRotation(this.head8, 0.0F, 0.0F, 0.122173F);
        this.head.addChild(this.head8);
        this.head9 = new ModelRenderer(this, 26, 22);
        this.head9.addBox(-3.0F, -1.0F, -8.0F, 1, 2, 1);
        this.head9.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head9.setTextureSize(32, 32);
        this.head9.mirror = true;
        this.setRotation(this.head9, 0.0F, 0.0F, -0.1047198F);
        this.head.addChild(this.head9);
        this.head10 = new ModelRenderer(this, 26, 22);
        this.head10.addBox(2.4F, -1.0F, -5.5F, 1, 1, 1);
        this.head10.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head10.setTextureSize(32, 32);
        this.head10.mirror = true;
        this.setRotation(this.head10, 0.0F, 0.0F, 0.0F);
        this.head.addChild(this.head10);
        this.head11 = new ModelRenderer(this, 26, 22);
        this.head11.addBox(-3.4F, -1.0F, -5.5F, 1, 1, 1);
        this.head11.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head11.setTextureSize(32, 32);
        this.head11.mirror = true;
        this.setRotation(this.head11, 0.0F, 0.0F, 0.0F);
        this.head.addChild(this.head11);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
    }

    public void render()
    {
        float par7 = 0.0625F;
        this.head.render(par7);
        this.body.render(par7);
        this.leftlegf.render(par7);
        this.leftleg.render(par7);
        this.rightlegf.render(par7);
        this.rightleg.render(par7);
    }
}
