package net.minecraft.client.addon.tchestplate;

import java.io.File;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Logger;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PostInit;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.Mod.ServerStarting;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;
import net.CFlag;
import net.minecraft.block.Block;
import net.minecraft.client.addon.tchestplate.accesories.items.AGH1;
import net.minecraft.client.addon.tchestplate.accesories.items.AGH2;
import net.minecraft.client.addon.tchestplate.accesories.items.AccesoriasBant;
import net.minecraft.client.addon.tchestplate.accesories.items.AccesoriasGirlHair;
import net.minecraft.client.addon.tchestplate.accesories.items.AccesoriasSanta;
import net.minecraft.client.addon.tchestplate.accesories.items.AccesoriasShut;
import net.minecraft.client.addon.tchestplate.accesories.items.AccesoriasSkull;
import net.minecraft.client.addon.tchestplate.accesories.items.AccesoriasVolk;
import net.minecraft.client.addon.tchestplate.accesories.items.Hellowen;
import net.minecraft.client.addon.tchestplate.aoc.Uham;
import net.minecraft.client.addon.tchestplate.armors.items.AngelBoots;
import net.minecraft.client.addon.tchestplate.armors.items.AngelChestPlate;
import net.minecraft.client.addon.tchestplate.armors.items.AngelHelmet;
import net.minecraft.client.addon.tchestplate.armors.items.AngelLeggins;
import net.minecraft.client.addon.tchestplate.armors.items.DemonBoots;
import net.minecraft.client.addon.tchestplate.armors.items.DemonChest;
import net.minecraft.client.addon.tchestplate.armors.items.DemonHelmet;
import net.minecraft.client.addon.tchestplate.armors.items.DemonLeggins;
import net.minecraft.client.addon.tchestplate.armors.items.LavaChestPlateBoots;
import net.minecraft.client.addon.tchestplate.armors.items.LavaChestPlateChest;
import net.minecraft.client.addon.tchestplate.armors.items.LavaChestPlateHelmet;
import net.minecraft.client.addon.tchestplate.armors.items.LavaChestPlateLeggins;
import net.minecraft.client.addon.tchestplate.armors.items.LavaPredatorPlateBoots;
import net.minecraft.client.addon.tchestplate.armors.items.LavaPredatorPlateChest;
import net.minecraft.client.addon.tchestplate.armors.items.LavaPredatorPlateHelmet;
import net.minecraft.client.addon.tchestplate.armors.items.LavaPredatorPlateLeggins;
import net.minecraft.client.addon.tchestplate.armors.items.LavaRBPlateBoots;
import net.minecraft.client.addon.tchestplate.armors.items.LavaRBPlateChest;
import net.minecraft.client.addon.tchestplate.armors.items.LavaRBPlateHelmet;
import net.minecraft.client.addon.tchestplate.armors.items.LavaRBPlateLeggins;
import net.minecraft.client.addon.tchestplate.armors.items.LavaShadowPlateBoots;
import net.minecraft.client.addon.tchestplate.armors.items.LavaShadowPlateChest;
import net.minecraft.client.addon.tchestplate.armors.items.LavaShadowPlateHelmet;
import net.minecraft.client.addon.tchestplate.armors.items.LavaShadowPlateLeggins;
import net.minecraft.client.addon.tchestplate.armors.items.LavaShadowPlateUBoots;
import net.minecraft.client.addon.tchestplate.armors.items.LavaShadowPlateUChest;
import net.minecraft.client.addon.tchestplate.armors.items.LavaShadowPlateUHelmet;
import net.minecraft.client.addon.tchestplate.armors.items.LavaShadowPlateULeggins;
import net.minecraft.client.addon.tchestplate.armors.items.LavaUltimaPlateBoots;
import net.minecraft.client.addon.tchestplate.armors.items.LavaUltimaPlateChest;
import net.minecraft.client.addon.tchestplate.armors.items.LavaUltimaPlateHelmet;
import net.minecraft.client.addon.tchestplate.armors.items.LavaUltimaPlateLeggins;
import net.minecraft.client.addon.tchestplate.armors.items.NoobPlateBoots;
import net.minecraft.client.addon.tchestplate.armors.items.NoobPlateChest;
import net.minecraft.client.addon.tchestplate.armors.items.NoobPlateHelmet;
import net.minecraft.client.addon.tchestplate.armors.items.NoobPlateLeggins;
import net.minecraft.client.addon.tchestplate.armors.items.OGNBoots;
import net.minecraft.client.addon.tchestplate.armors.items.OGNChest;
import net.minecraft.client.addon.tchestplate.armors.items.OGNHelmet;
import net.minecraft.client.addon.tchestplate.armors.items.OGNLeggins;
import net.minecraft.client.addon.tchestplate.armors.items.hc;
import net.minecraft.client.addon.tchestplate.blocks.AdamantiteOre;
import net.minecraft.client.addon.tchestplate.blocks.CobaltOre;
import net.minecraft.client.addon.tchestplate.blocks.PalladiumOre;
import net.minecraft.client.addon.tchestplate.donate.CommandDonate;
import net.minecraft.client.addon.tchestplate.donate.DonateManagerInv;
import net.minecraft.client.addon.tchestplate.entities.monster.EntityAW;
import net.minecraft.client.addon.tchestplate.entities.monster.EntityWisp;
import net.minecraft.client.addon.tchestplate.entities.projectile.EntityFrostBlue;
import net.minecraft.client.addon.tchestplate.entities.projectile.EntityFrostRed;
import net.minecraft.client.addon.tchestplate.entities.projectile.EntityGateCastle;
import net.minecraft.client.addon.tchestplate.entities.projectile.EntityGrenade;
import net.minecraft.client.addon.tchestplate.items.ItemAcceleratorMatter;
import net.minecraft.client.addon.tchestplate.items.ItemAmulets;
import net.minecraft.client.addon.tchestplate.items.ItemBracelets;
import net.minecraft.client.addon.tchestplate.items.ItemCP;
import net.minecraft.client.addon.tchestplate.items.ItemCPBox;
import net.minecraft.client.addon.tchestplate.items.ItemColorArmorSet;
import net.minecraft.client.addon.tchestplate.items.ItemCrystalAdamantite;
import net.minecraft.client.addon.tchestplate.items.ItemCrystalCobalt;
import net.minecraft.client.addon.tchestplate.items.ItemCrystalPalladium;
import net.minecraft.client.addon.tchestplate.items.ItemDonate;
import net.minecraft.client.addon.tchestplate.items.ItemKorona;
import net.minecraft.client.addon.tchestplate.items.ItemLavaBackPacks;
import net.minecraft.client.addon.tchestplate.items.ItemMaskHelmet;
import net.minecraft.client.addon.tchestplate.items.ItemPetograph;
import net.minecraft.client.addon.tchestplate.items.ItemPets;
import net.minecraft.client.addon.tchestplate.items.ItemShields;
import net.minecraft.client.addon.tchestplate.items.ItemTurning;
import net.minecraft.client.addon.tchestplate.modules.items.LavaBootsModule;
import net.minecraft.client.addon.tchestplate.modules.items.LavaChestModule;
import net.minecraft.client.addon.tchestplate.modules.items.LavaHelmetModule;
import net.minecraft.client.addon.tchestplate.modules.items.LavaLegginsModule;
import net.minecraft.client.addon.tchestplate.modules.items.Obm;
import net.minecraft.client.addon.tchestplate.modules.items.Ocm;
import net.minecraft.client.addon.tchestplate.modules.items.Ohm;
import net.minecraft.client.addon.tchestplate.modules.items.Olm;
import net.minecraft.client.addon.tchestplate.modules.items.PredatorBootsModule;
import net.minecraft.client.addon.tchestplate.modules.items.PredatorChestModule;
import net.minecraft.client.addon.tchestplate.modules.items.PredatorHelmetModule;
import net.minecraft.client.addon.tchestplate.modules.items.PredatorLegginsModule;
import net.minecraft.client.addon.tchestplate.packets.PacketHandlerMA;
import net.minecraft.client.addon.tchestplate.packets.PacketVelocityHook;
import net.minecraft.client.addon.tchestplate.util.Keyboard;
import net.minecraft.client.addon.tchestplate.weapon.items.HeroHammer;
import net.minecraft.client.addon.tchestplate.weapon.items.HeroSword;
import net.minecraft.client.addon.tchestplate.weapon.items.LFireSword;
import net.minecraft.client.addon.tchestplate.weapon.items.LHammer;
import net.minecraft.client.addon.tchestplate.weapon.items.LStaffFriz;
import net.minecraft.client.addon.tchestplate.weapon.items.LStaffFrize;
import net.minecraft.client.addon.tchestplate.weapon.items.LStaffSlowe;
import net.minecraft.client.addon.tchestplate.weapon.items.LStaffVedma;
import net.minecraft.client.addon.tchestplate.weapon.items.LStaffrbSlowe;
import net.minecraft.client.addon.tchestplate.weapon.items.LSwordPredator;
import net.minecraft.client.addon.tchestplate.weapon.items.LTomahawk;
import net.minecraft.client.addon.tchestplate.weapon.items.LrbHammer;
import net.minecraft.client.addon.tchestplate.weapon.items.LultimaHammer;
import net.minecraft.client.addon.tchestplate.weapon.items.Lvajra;
import net.minecraft.client.addon.tchestplate.weapon.items.NoobLsword;
import net.minecraft.client.addon.tchestplate.weapon.items.NoobLvajra;
import net.minecraft.client.addon.tchestplate.weapon.items.Pickaxe3x3;
import net.minecraft.client.addon.tchestplate.weapon.items.ShadowLMachete;
import net.minecraft.client.addon.tchestplate.weapon.items.ShadowLMacheteU;
import net.minecraft.client.addon.tchestplate.weapon.items.ShadowLancePika;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.entity.Entity;
import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.EnumToolMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemStack;
import net.minecraft.network.packet.Packet;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.EnumHelper;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.Property;
import org.bukkit.Bukkit;

@Mod(
   modid = "LavaChestPlate",
   name = "LavaChestPlate",
   version = "3.0.6",
   certificateFingerprint = "e43c2b0c74740c469df9c798fecd85541291695e81c34f3e0edd1a269f8da542"
)
@NetworkMod(
   clientSideRequired = true,
   serverSideRequired = false,
   channels = {"tc"},
   packetHandler = PacketHandlerMA.class
)
public class LavaChestPlate {

   @Instance("LavaChestPlate")
   public static LavaChestPlate instance;
   @SidedProxy(
      clientSide = "net.minecraft.client.addon.tchestplate.ClientProxy",
      serverSide = "net.minecraft.client.addon.tchestplate.ServerProxy"
   )
   public static ServerProxy proxy;
   @SidedProxy(
      clientSide = "net.minecraft.client.addon.tchestplate.util.KeyboardClient",
      serverSide = "net.minecraft.client.addon.tchestplate.util.Keyboard"
   )
   public static Keyboard keyboard;
   public static EnumToolMaterial TutMATERIAL = EnumHelper.addToolMaterial("TutMATERIAL", 2, 0, 7.0F, 30, 9);
   public static CreativeTabs tabArmor = new tabArmors(CreativeTabs.getNextID(), "tabUnder3");
   public static CreativeTabs tabItemss = new tabItemss(CreativeTabs.getNextID(), "tabUnder2");
   public static CreativeTabs tabUnder = new tabUnder(CreativeTabs.getNextID(), "tabUnder1");
   public static Item lHammer;
   public static Item lrbHammer;
   public static Item lultimaHammer;
   public static Item lvajra;
   public static Item[] itemLGen = new Item[2];
   public static Item lStaffFrize;
   public static Item lStaffSlowe;
   public static Item lStaffrbSlowe;
   public static Item laitemvedma;
   public static Item lShadowLMachete;
   public static boolean d = true;
   public static Item lShadowLancePika;
   public static int sum;
   public static int sh;
   public static int usum;
   public static int ush;
   public static Item lSwordPredator;
   public static Item lShadowLMacheteU;
   public static ItemArmor lavaChestPlateHelmet;
   public static ItemArmor lavaChestPlateChest;
   public static ItemArmor lavaChestPlateLeggins;
   public static ItemArmor lavaChestPlateBoots;
   public static ItemArmor lavaRBPlateHelmet;
   public static ItemArmor lavaRBPlateChest;
   public static ItemArmor DemonHelmet;
   public static ItemArmor DemonChest;
   public static ItemArmor DemonLeggins;
   public static ItemArmor DemonBoots;
   public static ItemArmor AngelHelm;
   public static ItemArmor AngelLeggins;
   public static ItemArmor AngelChestPlate;
   public static ItemArmor AngelBoots;
   public static ItemArmor lavaRBPlateLeggins;
   public static ItemArmor lavaRBPlateBoots;
   public static ItemArmor lavaUltimaPlateHelmet;
   public static ItemArmor lavaUltimaPlateChest;
   public static ItemArmor lavaUltimaPlateLeggins;
   public static ItemArmor lavaUltimaPlateBoots;
   public static ItemArmor noobPlateHelmet;
   public static ItemArmor noobPlateChest;
   public static ItemArmor noobPlateLeggins;
   public static ItemArmor noobPlateBoots;
   public static ItemArmor lavaShadowPlateHelmet;
   public static ItemArmor lavaShadowPlateChest;
   public static ItemArmor lavaShadowPlateLeggins;
   public static ItemArmor lavaShadowPlateBoots;
   public static ItemArmor hellowenA;
   public static ItemArmor hellowenChest;
   public static ItemArmor hellowenLeggens;
   public static Item itemMaskHelmet;
   public static ItemArmor hellowenBoots;
   public static ItemArmor AccesoriasBant;
   public static ItemArmor AccesoriasShut;
   public static ItemArmor AccesoriasVolk;
   public static ItemArmor AccesoriasGirlHair;
   public static Item[] scroll = new Item[16];
   public static ItemArmor gh1;
   public static ItemArmor gh2;
   public static Item lStaffVedma;
   public static ItemArmor AccesoriasSkull;
   public static ItemArmor lavaPredatorPlateHelmet;
   public static ItemArmor lavaPredatorPlateChest;
   public static ItemArmor lavaPredatorPlateLeggins;
   public static ItemArmor lavaPredatorPlateBoots;
   public static ItemArmor lavaShadowPlateUHelmet;
   public static ItemArmor lavaShadowPlateUChest;
   public static ItemArmor lavaShadowPlateULeggins;
   public static ItemArmor lavaShadowPlateUBoots;
   public static ItemArmor hc;
   public static Item crown;
   public static Item LTomahawk;
   public static ItemArmor OGN1;
   public static ItemArmor OGN2;
   public static ItemArmor OGN3;
   public static ItemArmor OGN4;
   public static Item shablon;
   public static Item itemCrystalAdamantite;
   public static Item itemCrystalCobalt;
   public static Item itemCrystalPalladium;
   public static Item itemTurning;
   public static Item itemAcceleratorMatter;
   public static Item ArmorColorSet;
   public static Item itemsArmorModules;
   public static Item energyPlate;
   public static Item darkPlate;
   public static Item diamondCaps;
   public static Block cobaltOre;
   public static Block palladiumOre;
   public static Block adamantiteOre;
   public static Item litemPets;
   public static Item litemShieldsWood;
   public static Item litemShieldsStil;
   public static Item litemShieldsDiamond;
   public static Item litemShieldsLava;
   public static Item litemShieldsLavaRB;
   public static Item litemShieldsLavaUltima;
   public static Item litemShieldsHunter;
   public static Item demon;
   public static Item litemShieldsDemon;
   public static Item litemPetograph;
   public static Item heroaxe;
   public static Item herosword;
   public static Item nooblvajra;
   public static Item itemLavaColorSet;
   public static Item nooblsword;
   public static Item itemAmulets;
   public static Item itemBracelet;
   public static DonateManagerInv instanceDonate;
   public static ItemArmor AccesoriasSanta;
   public static Item ItemDonate;
   public static Item itemCP;
   public static Item itemCPBox;
   public static Item i0;
   public static Item i1;
   public static Item i2;
   public static Item i3;
   public static Item i4;
   public static ItemArmor HaHead;
   public static ItemArmor HaGrud;
   public static ItemArmor HaLeg;
   public static ItemArmor HaBot;
   public static ItemArmor HaMask;
   public static ItemArmor HaMask2;
   public static ItemArmor DeerHelmet;
   public static Item uham;
   public static Item enderknife;
   public static Item itemColor;
   public static Item ItemKorona;
   public static Item pickAxe3x3;
   public static Item swordSupra;
   public static Item pickAxe1may;
   public static Item LFireSword;
   public static Enchantment enchPantera = null;
   public static int lava;
   public static int rb;
   public static int hunt;
   public static boolean is64pack;
   public static final Logger log = Logger.getLogger("Minecraft");
public static final Block accesorias23f = null;
   public EventHandler eventHandler;
   private ILavamobsProxy lavamobsproxy;
   public static Item itemKorona;
   public static Item herohammer;
   public static Item laitemfriz;
public static Item itemModule;
public static long syncTimeServer;
public static Item OGNMolot; 
   public static Item Umh;
   public static Item Umc;
   public static Item Uml;
   public static Item Umb;
   
   public static Item Hmh;
   public static Item Hmc; 
   public static Item Hml;
   public static Item Hmb;
   
   public static Item Omh;
   public static Item Omc; 
   public static Item Oml;
   public static Item Omb;
   public static Item itemBackPacks;
   @PreInit
   public void modPreLoad(FMLPreInitializationEvent event) throws Exception {
	
			
			
	  	
      Configuration cfg = new Configuration(new File(event.getModConfigurationDirectory(), "lava/seq.cfg"));
      cfg.load();
      if(instanceDonate == null) {
         instanceDonate = new DonateManagerInv(new File(event.getModConfigurationDirectory(), "lava/donate.conf"));
      }

      if(!Utils.isClient()) {
         Property hk = cfg.get("DEVIL", "CRAFT", "RU");
         PlayerDonateEvent.setKey(hk.getString());
      } else if(instanceDonate == null) {
         instanceDonate = new DonateManagerInv();
      }

      cfg.save();
      this.eventHandler = new EventHandler();
      MinecraftForge.EVENT_BUS.register(this.eventHandler);
      keyboard.load();
   }

   @PostInit
   public void modPostLoad(FMLPostInitializationEvent event) {
      instanceDonate.load();
   }

   private void configChestPlate(Configuration config) {
      lava = config.get("ArmorEnergy", "Lava", 2001).getInt();
      rb = config.get("ArmorEnergy", "RB", 3001).getInt();
      hunt = config.get("ArmorEnergy", "Hunter", 7001).getInt();
      sum = config.get("DamageSword", "ShadowSword", 200).getInt();
      usum = config.get("DamageSword", "UltimaShadowSword", 400).getInt();
      sh = config.get("ReturnEnergy", "Shadow", 10).getInt();
      ush = config.get("ReturnEnergy", "UltimaShadow", 20).getInt();
   }

   @Init
   public void modLoad(FMLInitializationEvent event) {
      laitemfriz = (new LStaffFriz(2233, 2, 15, EnumToolMaterial.EMERALD)).setUnlocalizedName("itemlavafrize").setCreativeTab(tabArmor);
      LanguageRegistry.addName(laitemfriz, "Посох Ангела");
      if(event.getSide().isClient()) {
         Packet.packetIdToClassMap.removeObject(28);
         Packet.addIdClassMapping(28, true, false, PacketVelocityHook.class);
      }
      new RayTrace();
      itemMaskHelmet = (new ItemMaskHelmet(3618, 5)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("itemMaskHelmet");
      LanguageRegistry.addName(new ItemStack(itemMaskHelmet, 1, 0), "Шапка Лава Ведьмы");
      LanguageRegistry.addName(new ItemStack(itemMaskHelmet, 1, 1), "Шапка Лава Военного");
      LanguageRegistry.addName(new ItemStack(itemMaskHelmet, 1, 3), "Шапка Лава школьника");
      LanguageRegistry.addName(new ItemStack(itemMaskHelmet, 1, 4), "Шапка Лава Деда Мороза");
      itemLavaColorSet = (new ItemColorArmorSet(3616, 1, 1)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("itemLavaColorSet");
      LanguageRegistry.addName(new ItemStack(itemLavaColorSet, 1, 0), "Палитра");
      
      
      Umh = (new LavaHelmetModule(6716)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Umh");
      LanguageRegistry.addName(new ItemStack(Umh, 1, 0), "Модуль ульт шлема");
      Umc = (new LavaChestModule(6717)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Umc");
      LanguageRegistry.addName(new ItemStack(Umc, 1, 0), "Модуль ульт нагрудника");
      Uml = (new LavaLegginsModule(6718)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Uml");
      LanguageRegistry.addName(new ItemStack(Uml, 1, 0), "Модуль ульт штанов");
      Umb = (new LavaBootsModule(6719)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Umb");
      LanguageRegistry.addName(new ItemStack(Umb, 1, 0), "Модуль ульт ботинок");
      
      Hmh = (new PredatorHelmetModule(6720)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Hmh");
      LanguageRegistry.addName(new ItemStack(Hmh, 1, 0), "Модуль хант шлема");
      Hmc = (new PredatorChestModule(6721)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Hmc");
      LanguageRegistry.addName(new ItemStack(Hmc, 1, 0), "Модуль хант нагрудника");
      Hml = (new PredatorLegginsModule(6722)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Hml");
      LanguageRegistry.addName(new ItemStack(Hml, 1, 0), "Модуль хант штанов");
      Hmb = (new PredatorBootsModule(6723)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Hmb");
      LanguageRegistry.addName(new ItemStack(Hmb, 1, 0), "Модуль хант ботинок");
      
      Omh = (new Ohm(6724)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Omh");
      LanguageRegistry.addName(new ItemStack(Omh, 1, 0), "Модуль огненного шлема");
      Omc = (new Ocm(6725)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Omc");
      LanguageRegistry.addName(new ItemStack(Omc, 1, 0), "Модуль огненного нагрудника");
      Oml = (new Olm(6726)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Oml");
      LanguageRegistry.addName(new ItemStack(Oml, 1, 0), "Модуль огненных штанов");
      Omb = (new Obm(6727)).setCreativeTab(CreativeTabs.tabMaterials).setUnlocalizedName("Omb");
      LanguageRegistry.addName(new ItemStack(Omb, 1, 0), "Модуль огненных ботинок");
      
      itemBackPacks = new ItemLavaBackPacks(2629, 2).setCreativeTab(CreativeTabs.tabCombat).setUnlocalizedName("itemBackPacks");
      LanguageRegistry.addName(new ItemStack(itemBackPacks, 1, 0), "Лава колчан");
      EntityRegistry.registerGlobalEntityID(EntityFrostBlue.class, "CentFrostShardBlue", EntityRegistry.findGlobalUniqueEntityId());
      EntityRegistry.registerModEntity(EntityFrostBlue.class, "CentFrostShardBlue", 0, this, 64, 20, true);
      LanguageRegistry.instance().addStringLocalization("entity.CentFrostShardBlue.name", "en_US", "CFrost Shard Blue");
      EntityRegistry.registerGlobalEntityID(EntityFrostRed.class, "CentFrostShardRed", EntityRegistry.findGlobalUniqueEntityId());
      EntityRegistry.registerModEntity(EntityFrostRed.class, "CentFrostShardRed", 1, this, 64, 20, true);
      LanguageRegistry.instance().addStringLocalization("entity.CentFrostShardRed.name", "en_US", "CFrost Shard Red");
      EntityRegistry.registerGlobalEntityID(EntityGateCastle.class, "entGateCastle", EntityRegistry.findGlobalUniqueEntityId());
      EntityRegistry.registerModEntity(EntityGateCastle.class, "entGateCastle", 2, this, 64, 20, true);
      LanguageRegistry.instance().addStringLocalization("entity.entGateCastle.name", "en_US", "Gate Castle");
      EntityRegistry.registerGlobalEntityID(EntityWisp.class, "entWispLava", EntityRegistry.findGlobalUniqueEntityId(), 5592405, 1131656);
      EntityRegistry.registerModEntity(EntityWisp.class, "entWispLava", 3, this, 64, 3, true);
      LanguageRegistry.instance().addStringLocalization("entity.entWispLava.name", "en_US", "WispLava");
      EntityRegistry.registerGlobalEntityID(EntityGrenade.class, "EntityGrenade", EntityRegistry.findGlobalUniqueEntityId());
      EntityRegistry.registerModEntity(EntityGrenade.class, "EntityGrenade", 4, this, 64, 20, true);
      LanguageRegistry.instance().addStringLocalization("entity.EntityGrenade.name", "en_US", "EntityGrenade");
      EntityRegistry.registerGlobalEntityID(EntityAW.class, "entAW", EntityRegistry.findGlobalUniqueEntityId(), 5592405, 1131656);
      EntityRegistry.registerModEntity(EntityAW.class, "entAW", 5, this, 64, 3, true);
      lavaChestPlateHelmet = (ItemArmor)(new LavaChestPlateHelmet(2200, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("LavaHelmet");
      lavaChestPlateChest = (ItemArmor)(new LavaChestPlateChest(2201, EnumArmorMaterial.DIAMOND, 1, 1)).setUnlocalizedName("LavaChest");
      lavaChestPlateLeggins = (ItemArmor)(new LavaChestPlateLeggins(2202, EnumArmorMaterial.DIAMOND, 2, 2)).setUnlocalizedName("LavaLeggins");
      lavaChestPlateBoots = (ItemArmor)(new LavaChestPlateBoots(2203, EnumArmorMaterial.DIAMOND, 3, 3)).setUnlocalizedName("LavaBoots");
      AccesoriasBant = (ItemArmor)(new AccesoriasBant(2204, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("LavaBant");
      AccesoriasShut = (ItemArmor)(new AccesoriasShut(2205, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("LavaShut");
      lavaRBPlateHelmet = (ItemArmor)(new LavaRBPlateHelmet(2206, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("LavaRBHelmet");
      lavaRBPlateChest = (ItemArmor)(new LavaRBPlateChest(2207, EnumArmorMaterial.DIAMOND, 1, 1)).setUnlocalizedName("LavaRBChest");
      lavaRBPlateLeggins = (ItemArmor)(new LavaRBPlateLeggins(2208, EnumArmorMaterial.DIAMOND, 2, 2)).setUnlocalizedName("LavaRBLeggins");
      lavaRBPlateBoots = (ItemArmor)(new LavaRBPlateBoots(2209, EnumArmorMaterial.DIAMOND, 3, 3)).setUnlocalizedName("LavaRBBoots");
      AccesoriasVolk = (ItemArmor)(new AccesoriasVolk(2210, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("LavaVolk");
      LanguageRegistry.addName(AccesoriasBant, "Лава Бант");
      LanguageRegistry.addName(AccesoriasShut, "Лава Шут");
      LanguageRegistry.addName(AccesoriasVolk, "Лава Волк");
      LanguageRegistry.addName(lavaChestPlateBoots, "Лава Ботинки");
      LanguageRegistry.addName(lavaChestPlateChest, "Лава Нагрудник");
      LanguageRegistry.addName(lavaChestPlateHelmet, "Лава Шлем");
      LanguageRegistry.addName(lavaChestPlateLeggins, "Лава Штаны");
      LanguageRegistry.addName(lavaRBPlateBoots, "Лава РБ Ботинки");
      LanguageRegistry.addName(lavaRBPlateChest, "Лава РБ Нагрудник");
      LanguageRegistry.addName(lavaRBPlateHelmet, "Лава РБ Шлем");
      LanguageRegistry.addName(lavaRBPlateLeggins, "Лава РБ Штаны");
      OGN4 = (ItemArmor)(new OGNHelmet(2912, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("OGN4");
      OGN3 = (ItemArmor)(new OGNChest(2913, EnumArmorMaterial.DIAMOND, 1, 1)).setUnlocalizedName("OGN3");
      OGN2 = (ItemArmor)(new OGNLeggins(2914, EnumArmorMaterial.DIAMOND, 2, 2)).setUnlocalizedName("OGN2");
      OGN1 = (ItemArmor)(new OGNBoots(2915, EnumArmorMaterial.DIAMOND, 3, 3)).setUnlocalizedName("OGN1");
      LFireSword = (new LFireSword(2916)).setCreativeTab(LavaChestPlate.tabArmor).setUnlocalizedName("lfiresword");
      LanguageRegistry.addName(LFireSword, "Лава огненный меч");     		  
      LanguageRegistry.addName(OGN4, "Огненный шлем");
      LanguageRegistry.addName(OGN3, "Огненный нагрудник");
      LanguageRegistry.addName(OGN2, "Огненные поножи");
      LanguageRegistry.addName(OGN1, "Огненные ботинки");
      itemCrystalAdamantite = (new ItemCrystalAdamantite(2213, 64, 2)).setCreativeTab(tabItemss).setUnlocalizedName("itemCrystalAdamantite");
      LanguageRegistry.addName(new ItemStack(itemCrystalAdamantite, 1, 0), "Адамантитовый кристал");
      LanguageRegistry.addName(new ItemStack(itemCrystalAdamantite, 1, 1), "Огранённый Адамантитовый кристалл");
      itemCrystalCobalt = (new ItemCrystalCobalt(2214, 64, 3)).setCreativeTab(tabItemss).setUnlocalizedName("itemCrystalCobalt");
      LanguageRegistry.addName(new ItemStack(itemCrystalCobalt, 1, 0), "Кобальтовый кристал");
      LanguageRegistry.addName(new ItemStack(itemCrystalCobalt, 1, 1), "Огранённый Кобальтовый кристалл");
      LanguageRegistry.addName(new ItemStack(itemCrystalCobalt, 1, 2), "Праздничная конфета");
      itemCrystalPalladium = (new ItemCrystalPalladium(2215, 64, 3)).setCreativeTab(tabItemss).setUnlocalizedName("itemCrystalPalladium");
      LanguageRegistry.addName(new ItemStack(itemCrystalPalladium, 1, 0), "Палладиевый кристалл");
      LanguageRegistry.addName(new ItemStack(itemCrystalPalladium, 1, 1), "Огранённый Палладиевый кристалл");
      LanguageRegistry.addName(new ItemStack(itemCrystalPalladium, 1, 2), "Лава Койн");
      itemKorona = (new ItemKorona(3573, 2)).setCreativeTab(CreativeTabs.tabCombat).setUnlocalizedName("itemKorona");
      LanguageRegistry.addName(new ItemStack(itemKorona, 1, 0), "Огненная корона");
      LanguageRegistry.addName(new ItemStack(itemKorona, 1, 1), "Дьявол корона");
      itemTurning = (new ItemTurning(2216, 64, 16)).setCreativeTab(tabItemss).setUnlocalizedName("itemTurning");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 0), "Пустая капсула");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 1), "Капсула с водой");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 2), "Капсула с нагретой водой");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 3), "Кристаллическая пыль");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 4), "Кристаллическая сварка");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 5), "Адамантитовая основа");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 6), "Продвинутая адамантитовая основа");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 7), "Огранённый адамантитовый монолит");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 8), "Палладиевая пластина");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 9), "Огранённая палладиевая пластина");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 10), "Огранённый палладиевый монолит");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 11), "Уплотнённая палладиевая пластина");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 12), "Кобальтовый материал");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 13), "Капсула с материей");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 14), "Базовая капсула с материей");
      LanguageRegistry.addName(new ItemStack(itemTurning, 1, 15), "Начальная капсула с материей");
      LTomahawk = (new LTomahawk(3333, TutMATERIAL)).setUnlocalizedName("LTomahawkLTomahawkLTomahawk");
      LanguageRegistry.addName(LTomahawk, "Лава Огненный Молот");
      GameRegistry.registerBlock(adamantiteOre = (new AdamantiteOre(2216)).setHardness(3.0F).setResistance(5.0F).setCreativeTab(CreativeTabs.tabBlock).setUnlocalizedName("adamantiteOre"), "AdamantiteOre");
      GameRegistry.registerBlock(palladiumOre = (new PalladiumOre(2217)).setHardness(3.0F).setResistance(5.0F).setCreativeTab(CreativeTabs.tabBlock).setUnlocalizedName("palladiumOre"), "PalladiumOre");
      GameRegistry.registerBlock(cobaltOre = (new CobaltOre(2218)).setHardness(3.0F).setResistance(5.0F).setCreativeTab(CreativeTabs.tabBlock).setUnlocalizedName("cobaltOre"), "CobaltOre");
      LanguageRegistry.addName(adamantiteOre, "Адамантитовая руда");
      LanguageRegistry.addName(palladiumOre, "Палладиевая руда");
      LanguageRegistry.addName(cobaltOre, "Кобальтовая руда");
      LanguageRegistry.addName(AccesoriasGirlHair = (ItemArmor)(new AccesoriasGirlHair(2219, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("AccesoriasGirlHair"), "Прическа Девочки");
      lHammer = (new LHammer(2220, TutMATERIAL)).setUnlocalizedName("lHammer");
      lrbHammer = (new LrbHammer(2221, TutMATERIAL)).setUnlocalizedName("lrbHammer");
      lultimaHammer = (new LultimaHammer(2222, TutMATERIAL)).setUnlocalizedName("lultimaHammer");
      LanguageRegistry.addName(lHammer, "Лава молот");
      LanguageRegistry.addName(lrbHammer, "Лава РБ молот");
      LanguageRegistry.addName(lultimaHammer, "Лава Ультима молот");
      LanguageRegistry.addName(AccesoriasSkull = (ItemArmor)(new AccesoriasSkull(2223, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("AccesoriasSkull"), "Лава Череп");
      lavaUltimaPlateHelmet = (ItemArmor)(new LavaUltimaPlateHelmet(2224, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("LavaUltimaHelmet");
      lavaUltimaPlateChest = (ItemArmor)(new LavaUltimaPlateChest(2225, EnumArmorMaterial.DIAMOND, 1, 1)).setUnlocalizedName("LavaUltimaChest");
      lavaUltimaPlateLeggins = (ItemArmor)(new LavaUltimaPlateLeggins(2226, EnumArmorMaterial.DIAMOND, 2, 2)).setUnlocalizedName("LavaUltimaLeggins");
      LanguageRegistry.addName(lavaUltimaPlateBoots = (ItemArmor)(new LavaUltimaPlateBoots(2227, EnumArmorMaterial.DIAMOND, 3, 3)).setUnlocalizedName("LavaUltimaBoots"), "Лава Ультима Ботинки");
      LanguageRegistry.addName(lavaUltimaPlateChest, "Лава Ультима Нагрудник");
      LanguageRegistry.addName(lavaUltimaPlateHelmet, "Лава Ультима Шлем");
      LanguageRegistry.addName(lavaUltimaPlateLeggins, "Лава Ультима Штаны");
      lavaPredatorPlateHelmet = (ItemArmor)(new LavaPredatorPlateHelmet(2571, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("LavaPredatorHelmet");
      lavaPredatorPlateChest = (ItemArmor)(new LavaPredatorPlateChest(2572, EnumArmorMaterial.DIAMOND, 1, 1)).setUnlocalizedName("LavaPredatorChest");
      lavaPredatorPlateLeggins = (ItemArmor)(new LavaPredatorPlateLeggins(2573, EnumArmorMaterial.DIAMOND, 2, 2)).setUnlocalizedName("LavaPredatorLeggins");
      lavaPredatorPlateBoots = (ItemArmor)(new LavaPredatorPlateBoots(2575, EnumArmorMaterial.DIAMOND, 3, 3)).setUnlocalizedName("LavaPredatorBoots");
      LanguageRegistry.addName(lavaPredatorPlateBoots, "Лава Хантер Ботинки");
      LanguageRegistry.addName(lavaPredatorPlateChest, "Лава Хантер Нагрудник");
      LanguageRegistry.addName(lavaPredatorPlateHelmet, "Лава Хантер Шлем");
      LanguageRegistry.addName(lavaPredatorPlateLeggins, "Лава Хантер Штаны");
      lavaShadowPlateUHelmet = (ItemArmor)(new LavaShadowPlateUHelmet(2566, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("LavaShadowHelmetU");
      lavaShadowPlateUChest = (ItemArmor)(new LavaShadowPlateUChest(2567, EnumArmorMaterial.DIAMOND, 1, 1)).setUnlocalizedName("LavaShadowChestU");
      lavaShadowPlateULeggins = (ItemArmor)(new LavaShadowPlateULeggins(2568, EnumArmorMaterial.DIAMOND, 2, 2)).setUnlocalizedName("LavaShadowLegginsU");
      lavaShadowPlateUBoots = (ItemArmor)(new LavaShadowPlateUBoots(2569, EnumArmorMaterial.DIAMOND, 3, 3)).setUnlocalizedName("LavaShadowBootsU");
      LanguageRegistry.addName(lavaShadowPlateUBoots, "Лава Сумрачные Ботинки Ультима");
      LanguageRegistry.addName(lavaShadowPlateUChest, "Лава Сумрачные Нагрудник Ультима");
      LanguageRegistry.addName(lavaShadowPlateUHelmet, "Лава Сумрачные Шлем Ультима");
      LanguageRegistry.addName(lavaShadowPlateULeggins, "Лава Сумрачные Штаны Ультима");
      lSwordPredator = (new LSwordPredator(2599)).setUnlocalizedName("lSwordPredator");
      LanguageRegistry.addName(lSwordPredator, "Лава хантер лезвие");
      lShadowLMacheteU = (new ShadowLMacheteU(2570)).setUnlocalizedName("itemlShadowLMacheteU");
      LanguageRegistry.addName(lShadowLMacheteU, "Лава Сумеречный меч Ультима");
      itemAcceleratorMatter = (new ItemAcceleratorMatter(2228, 1, 12)).setCreativeTab(tabItemss).setUnlocalizedName("itemAcceleratorMatter");
      pickAxe3x3 = (new Pickaxe3x3(4634, EnumToolMaterial.EMERALD)).setUnlocalizedName("3X3pick");
      LanguageRegistry.addName(pickAxe3x3, "Лава Кирка Разрушитель");
      LanguageRegistry.addName(new ItemStack(itemAcceleratorMatter, 1, 0), "Ускоритель частиц 1го уровня");
      LanguageRegistry.addName(new ItemStack(itemAcceleratorMatter, 1, 1), "Ускоритель частиц 2го уровня");
      LanguageRegistry.addName(new ItemStack(itemAcceleratorMatter, 1, 2), "Ускоритель частиц 3го уровня");
      LanguageRegistry.addName(new ItemStack(itemAcceleratorMatter, 1, 3), "Ускоритель частиц 4го уровня");
      LanguageRegistry.addName(new ItemStack(itemAcceleratorMatter, 1, 4), "Ускоритель частиц 5го уровня");
      LanguageRegistry.addName(new ItemStack(itemAcceleratorMatter, 1, 5), "Ускоритель частиц 6го уровня");
      LanguageRegistry.addName(new ItemStack(itemAcceleratorMatter, 1, 6), "Ускоритель частиц 7го уровня");
      LanguageRegistry.addName(new ItemStack(itemAcceleratorMatter, 1, 7), "Ускоритель частиц 8го уровня");
      LanguageRegistry.addName(new ItemStack(itemAcceleratorMatter, 1, 8), "Ускоритель частиц 9го уровня");
      LanguageRegistry.addName(new ItemStack(itemAcceleratorMatter, 1, 9), "Ускоритель частиц 10го уровня");
      LanguageRegistry.addName(new ItemStack(itemAcceleratorMatter, 1, 10), "Ускоритель частиц 11го уровня");
      LanguageRegistry.addName(lvajra = (new Lvajra(2229, EnumToolMaterial.EMERALD)).setUnlocalizedName("itemlavavajra"), "Лава Разрушитель");
      litemPets = (new ItemPets(2234, 1, 10)).setCreativeTab(tabItemss).setUnlocalizedName("litemPets");
      LanguageRegistry.addName(new ItemStack(litemPets, 1, 0), "Питомец Зомби");
      LanguageRegistry.addName(new ItemStack(litemPets, 1, 1), "Питомец Ангел");
      LanguageRegistry.addName(new ItemStack(litemPets, 1, 2), "Питомец Монстер");
      LanguageRegistry.addName(new ItemStack(litemPets, 1, 3), "Питомец Миньон");
      LanguageRegistry.addName(new ItemStack(litemPets, 1, 4), "Питомец Пикачу");
      LanguageRegistry.addName(new ItemStack(litemPets, 1, 5), "Питомец Майк");
      LanguageRegistry.addName(new ItemStack(litemPets, 1, 6), "Питомец Зайка");
      LanguageRegistry.addName(new ItemStack(litemPets, 1, 7), "Питомец Чужой");
      LanguageRegistry.addName(new ItemStack(litemPets, 1, 8), "Питомец Смурфик");
      LanguageRegistry.addName(new ItemStack(litemPets, 1, 9), "Питомец Ведьма");
      litemPetograph = (new ItemPetograph(2235, 1, 1)).setCreativeTab(tabItemss).setUnlocalizedName("itemPetograph");
      LanguageRegistry.addName(new ItemStack(litemPetograph, 1, 0), "Питограф");
      LanguageRegistry.addName(litemShieldsWood = (new ItemShields(2236, 1.0F, 200, 0)).setCreativeTab(tabItemss).setUnlocalizedName("itemShieldWood"), "Деревянный Щит");
      LanguageRegistry.addName(litemShieldsStil = (new ItemShields(2237, 2.0F, 1000, 1)).setCreativeTab(tabItemss).setUnlocalizedName("itemShieldsStil"), "Железный Щит");
      LanguageRegistry.addName(litemShieldsDiamond = (new ItemShields(2238, 3.0F, 5000, 2)).setCreativeTab(tabItemss).setUnlocalizedName("itemShieldsDiamond"), "Алмазный Щит");
      LanguageRegistry.addName(litemShieldsLava = (new ItemShields(2239, 15.0F, 10000, 3)).setCreativeTab(tabItemss).setUnlocalizedName("itemShieldsLava"), "Лава Щит");
      LanguageRegistry.addName(litemShieldsLavaRB = (new ItemShields(2240, 20.0F, 20000, 4)).setCreativeTab(tabItemss).setUnlocalizedName("itemShieldsLavaRB"), "Лава РБ Щит");
      LanguageRegistry.addName(litemShieldsLavaUltima = (new ItemShields(2241, 25.0F, 100000, 5)).setCreativeTab(tabItemss).setUnlocalizedName("itemShieldsLavaUltima"), "Лава Ультима Щит");
      LanguageRegistry.addName(litemShieldsHunter = (new ItemShields(2242, 30.0F, 100000, 6)).setCreativeTab(tabItemss).setUnlocalizedName("itemShieldsHunter"), "Хантер щит");
      LanguageRegistry.addName(litemShieldsDemon = (new ItemShields(2243, 30.0F, 100000, 7)).setCreativeTab(tabItemss).setUnlocalizedName("itemShieldsDemon"), "Демон щит");
      noobPlateHelmet = (ItemArmor)(new NoobPlateHelmet(2542, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("NoobHelmet");
      noobPlateChest = (ItemArmor)(new NoobPlateChest(2543, EnumArmorMaterial.DIAMOND, 1, 1)).setUnlocalizedName("NoobChest");
      noobPlateLeggins = (ItemArmor)(new NoobPlateLeggins(2544, EnumArmorMaterial.DIAMOND, 2, 2)).setUnlocalizedName("NoobLeggins");
      LanguageRegistry.addName(noobPlateBoots = (ItemArmor)(new NoobPlateBoots(2545, EnumArmorMaterial.DIAMOND, 3, 3)).setUnlocalizedName("NoobBoots"), "Нуб Ботинки");
      LanguageRegistry.addName(noobPlateChest, "Нуб Нагрудник");
      LanguageRegistry.addName(noobPlateHelmet, "Нуб Шлем");
      LanguageRegistry.addName(noobPlateLeggins, "Нуб Штаны");
      LanguageRegistry.addName(nooblvajra = (new NoobLvajra(2546, EnumToolMaterial.EMERALD)).setUnlocalizedName("itemnooblavavajra"), "Нуб Разрушитель");
      LanguageRegistry.addName(nooblsword = (new NoobLsword(2547)).setUnlocalizedName("itemnooblsword"), "Нуб меч");
      itemAmulets = (new ItemAmulets(2548, 12)).setCreativeTab(tabItemss).setUnlocalizedName("itemAmulets");
      LanguageRegistry.addName(new ItemStack(itemAmulets, 1, 0), "Деревянный амулет");
      LanguageRegistry.addName(new ItemStack(itemAmulets, 1, 1), "Железный амулет");
      LanguageRegistry.addName(new ItemStack(itemAmulets, 1, 2), "Алмазный амулет");
      LanguageRegistry.addName(new ItemStack(itemAmulets, 1, 3), "Лава амулет");
      LanguageRegistry.addName(new ItemStack(itemAmulets, 1, 4), "Лава РБ амулет");
      LanguageRegistry.addName(new ItemStack(itemAmulets, 1, 5), "Лава Ультима амулет");
      LanguageRegistry.addName(new ItemStack(itemAmulets, 1, 6), "Хантер амулет");
      LanguageRegistry.addName(new ItemStack(itemAmulets, 1, 7), "Демон амулет");
      LanguageRegistry.addName(new ItemStack(itemAmulets, 1, 8), "Лава амулет черной пантеры");
      LanguageRegistry.addName(new ItemStack(itemAmulets, 1, 9), "Георгиевская ленточка");
      LanguageRegistry.addName(new ItemStack(itemAmulets, 1, 10), "Амулет ведьмы");
      demon = (new Demonic(8285)).setCreativeTab(LavaChestPlate.tabArmor).setUnlocalizedName("demonic");
      LanguageRegistry.addName(demon, "Дьявол меч");
      itemBracelet = (new ItemBracelets(2549, 10)).setCreativeTab(tabItemss).setUnlocalizedName("itemBracelet");
      LanguageRegistry.addName(new ItemStack(itemBracelet, 1, 0), "Деревянный браслет");
      LanguageRegistry.addName(new ItemStack(itemBracelet, 1, 1), "Железный браслет");
      LanguageRegistry.addName(new ItemStack(itemBracelet, 1, 2), "Алмазный браслет");
      LanguageRegistry.addName(new ItemStack(itemBracelet, 1, 3), "Лава браслет");
      LanguageRegistry.addName(new ItemStack(itemBracelet, 1, 4), "Лава РБ браслет");
      LanguageRegistry.addName(new ItemStack(itemBracelet, 1, 5), "Лава Ультима браслет");
      LanguageRegistry.addName(new ItemStack(itemBracelet, 1, 6), "Хантер браслет");
      LanguageRegistry.addName(new ItemStack(itemBracelet, 1, 7), "Демон браслет");
      LanguageRegistry.addName(new ItemStack(itemBracelet, 1, 8), "Ангел браслет");
      LanguageRegistry.addName(new ItemStack(itemBracelet, 1, 9), "Ведьма браслет");
   
      DemonHelmet = (ItemArmor)(new DemonHelmet(6101, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("PredathgdoasdasdrHelmets");
      DemonChest = (ItemArmor)(new DemonChest(6102, EnumArmorMaterial.DIAMOND, 1, 1)).setUnlocalizedName("PredataaafgorChasdasdests");
      DemonLeggins = (ItemArmor)(new DemonLeggins(6103, EnumArmorMaterial.DIAMOND, 2, 2)).setUnlocalizedName("PredaatorLegasdasdginss");
      DemonBoots = (ItemArmor)(new DemonBoots(6104, EnumArmorMaterial.DIAMOND, 3, 3)).setUnlocalizedName("LPredatorasdBoosaasdts");
      LanguageRegistry.addName(DemonHelmet, "Демон шлем");
      LanguageRegistry.addName(DemonChest, "Демон нагрудник");
      LanguageRegistry.addName(DemonLeggins, "Демон штаны");
      LanguageRegistry.addName(DemonBoots, "Демон ботинки");
      
      laitemvedma = (new LStaffVedma(6105, 2, 15, EnumToolMaterial.EMERALD)).setUnlocalizedName("itemlavavedma").setCreativeTab(tabArmor);
      LanguageRegistry.addName(laitemvedma, "Посох Ведьмы");
      
      AngelHelm = (ItemArmor)(new AngelHelmet(6109, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("AngelXyina").setCreativeTab(tabArmor);
      AngelLeggins = (ItemArmor)(new AngelLeggins(6111, EnumArmorMaterial.DIAMOND, 2, 2)).setUnlocalizedName("AngelXyina1").setCreativeTab(tabArmor);
      AngelChestPlate = (ItemArmor)(new AngelChestPlate(6110, EnumArmorMaterial.DIAMOND, 1, 1)).setUnlocalizedName("AngelXyina2").setCreativeTab(tabArmor);
      AngelBoots = (ItemArmor)(new AngelBoots(6112, EnumArmorMaterial.DIAMOND, 3, 3)).setUnlocalizedName("AngelXyina3").setCreativeTab(tabArmor);
      LanguageRegistry.addName(AngelHelm, "Ангел Корона");
      LanguageRegistry.addName(AngelChestPlate, "Ангел Нагрудник");
      LanguageRegistry.addName(AngelLeggins, "Ангел Штаны");
      LanguageRegistry.addName(AngelBoots, "Ангел Ботинки");
      
      
      hellowenA = (ItemArmor)(new Hellowen(2550, EnumArmorMaterial.DIAMOND, 0, 0, 6, 0)).setUnlocalizedName("itemHellowen");
      LanguageRegistry.addName(new ItemStack(hellowenA, 1, 0), "маска монстра");
      LanguageRegistry.addName(new ItemStack(hellowenA, 1, 1), "маска клоуна");
      LanguageRegistry.addName(new ItemStack(hellowenA, 1, 2), "маска зомби");
      LanguageRegistry.addName(new ItemStack(hellowenA, 1, 3), "маска ганибала");
      LanguageRegistry.addName(new ItemStack(hellowenA, 1, 4), "Наряд девочки Заколка");
      LanguageRegistry.addName(new ItemStack(hellowenA, 1, 5), "Наряд мальчика Бутоньерка");
      hellowenChest = (ItemArmor)(new Hellowen(2552, EnumArmorMaterial.DIAMOND, 1, 1, 2, 6)).setUnlocalizedName("itemHellowenChest");
      LanguageRegistry.addName(new ItemStack(hellowenChest, 1, 0), "Наряд девочки Сорочка");
      LanguageRegistry.addName(new ItemStack(hellowenChest, 1, 1), "Наряд мальчика Пиджак");
      hellowenLeggens = (ItemArmor)(new Hellowen(2553, EnumArmorMaterial.DIAMOND, 2, 2, 2, 8)).setUnlocalizedName("itemHellowenLeggens");
      LanguageRegistry.addName(new ItemStack(hellowenLeggens, 1, 0), "Наряд девочки Юбка");
      LanguageRegistry.addName(new ItemStack(hellowenLeggens, 1, 1), "Наряд мальчика Брюки");
      hellowenBoots = (ItemArmor)(new Hellowen(2554, EnumArmorMaterial.DIAMOND, 3, 3, 2, 10)).setUnlocalizedName("itemHellowenBoots");
      LanguageRegistry.addName(new ItemStack(hellowenBoots, 1, 0), "Наряд девочки Туфли");
      LanguageRegistry.addName(new ItemStack(hellowenBoots, 1, 1), "Наряд мальчика Туфли");
      LanguageRegistry.addName(AccesoriasSanta = (ItemArmor)(new AccesoriasSanta(2555, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("LavaSanta"), "Шапка Деда мороза");
      ItemDonate = (new ItemDonate(2556, 2)).setCreativeTab(tabItemss).setUnlocalizedName("itemDonate");
      LanguageRegistry.addName(new ItemStack(ItemDonate, 1, 0), "Лава Купон");
      LanguageRegistry.addName(new ItemStack(ItemDonate, 1, 1), "Лава Койн");
      lavaShadowPlateHelmet = (ItemArmor)(new LavaShadowPlateHelmet(2557, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("LavaShadowHelmet");
      lavaShadowPlateChest = (ItemArmor)(new LavaShadowPlateChest(2558, EnumArmorMaterial.DIAMOND, 1, 1)).setUnlocalizedName("LavaShadowChest");
      lavaShadowPlateLeggins = (ItemArmor)(new LavaShadowPlateLeggins(2559, EnumArmorMaterial.DIAMOND, 2, 2)).setUnlocalizedName("LavaShadowLeggins");
      LanguageRegistry.addName(lavaShadowPlateBoots = (ItemArmor)(new LavaShadowPlateBoots(2560, EnumArmorMaterial.DIAMOND, 3, 3)).setUnlocalizedName("LavaShadowBoots"), "Лава Сумрачные Ботинки");
      LanguageRegistry.addName(lavaShadowPlateChest, "Лава Сумрачные Нагрудник");
      LanguageRegistry.addName(lavaShadowPlateHelmet, "Лава Сумрачные Шлем");
      LanguageRegistry.addName(lavaShadowPlateLeggins, "Лава Сумрачные Штаны");
      LanguageRegistry.addName(lShadowLMachete = (new ShadowLMachete(2561)).setUnlocalizedName("itemlShadowLMachete"), "Лава Сумеречный меч");
      LanguageRegistry.addName(lShadowLancePika = (new ShadowLancePika(2562)).setUnlocalizedName("itemlShadowLancePika"), "Лава Сумеречная пика");
      itemCP = (new ItemCP(2563, 5)).setCreativeTab(tabArmor).setUnlocalizedName("itemCP");
      LanguageRegistry.addName(new ItemStack(itemCP, 1, 0), "Пузырёк с лава энергией 1ур");
      LanguageRegistry.addName(new ItemStack(itemCP, 1, 1), "Пузырёк с лава энергией 2ур");
      LanguageRegistry.addName(new ItemStack(itemCP, 1, 2), "Пузырёк с лава энергией 3ур");
      LanguageRegistry.addName(new ItemStack(itemCP, 1, 3), "Пузырёк с лава энергией 4ур");
      LanguageRegistry.addName(new ItemStack(itemCP, 1, 4), "Пузырёк с лава энергией 5ур");
      itemCPBox = (new ItemCPBox(2564, 5)).setCreativeTab(tabArmor).setUnlocalizedName("itemCPBox");
      LanguageRegistry.addName(new ItemStack(itemCPBox, 1, 0), "Коробка с Пузырьками лава энергии 1ур");
      LanguageRegistry.addName(new ItemStack(itemCPBox, 1, 1), "Коробка с Пузырьками лава энергии 2ур");
      LanguageRegistry.addName(new ItemStack(itemCPBox, 1, 2), "Коробка с Пузырьками лава энергии 3ур");
      LanguageRegistry.addName(new ItemStack(itemCPBox, 1, 3), "Коробка с Пузырьками лава энергии 4ур");
      LanguageRegistry.addName(new ItemStack(itemCPBox, 1, 4), "Коробка с Пузырьками лава энергии 5ур");
      uham = (new Uham(6301, TutMATERIAL)).setUnlocalizedName("uhamR");
      LanguageRegistry.addName(uham, "Ультима сумрачный молот");
      herosword = (new HeroSword(6315)).setUnlocalizedName("DB614154513682717");
      LanguageRegistry.addName(herosword, "Меч героя");
      LanguageRegistry.addName(gh1 = (ItemArmor)(new AGH1(2601, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("AccesoriasGirlHair1"), "Прическа Девочки Фиолетовая");
      LanguageRegistry.addName(gh2 = (ItemArmor)(new AGH2(2602, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("AccesoriasGirlHair2"), "Прическа Девочки Синяя");
      lStaffFrize = (new LStaffFrize(2230, 4, 10, EnumToolMaterial.EMERALD)).setUnlocalizedName("itemlavafriz").setCreativeTab(tabArmor);
      LanguageRegistry.addName(lStaffFrize, "Посох шока");
      lStaffSlowe = (new LStaffSlowe(2231, 2, 2, EnumToolMaterial.EMERALD)).setUnlocalizedName("itemlavaslowe").setCreativeTab(tabArmor);
      LanguageRegistry.addName(lStaffSlowe, "Синии посох замедления");
      lStaffrbSlowe = (new LStaffrbSlowe(2232, 5, 2, EnumToolMaterial.EMERALD)).setUnlocalizedName("itemlavarbslowe").setCreativeTab(tabArmor);
      LanguageRegistry.addName(lStaffrbSlowe, "Красный посох замедления");
      heroaxe = (new HeroHammer(6316, TutMATERIAL)).setUnlocalizedName("DB17509175897651");
      LanguageRegistry.addName(heroaxe, "Топор героя");
      hc = (ItemArmor)(new hc(2615, EnumArmorMaterial.DIAMOND, 0, 0)).setUnlocalizedName("nyllevoi");
      LanguageRegistry.addName(hc, "Корона героя");
      ItemStack u = new ItemStack(21163, 1, 0);
      ItemStack uu = new ItemStack(21164, 1, 0);
      new ItemStack(itemTurning, 1, 5);
      ItemStack app = new ItemStack(itemTurning, 1, 6);
      new ItemStack(itemTurning, 1, 13);
      new ItemStack(itemCrystalCobalt, 1, 1);
      new ItemStack(itemBracelet, 1, 4);
      new ItemStack(litemShieldsLavaRB, 1);
      new ItemStack(itemAmulets, 1, 4);
      ItemStack tbup = new ItemStack(2399, 1, 0);
      ItemStack tbpress = new ItemStack(2617, 1, 0);
      ItemStack sb = new ItemStack(20977, 1, 5);
      ItemStack sbt = new ItemStack(20977, 1, 2);
      new ItemStack(itemAmulets, 1, 5);
      new ItemStack(itemBracelet, 1, 5);
      new ItemStack(litemShieldsLavaUltima, 1);
      ItemStack press = new ItemStack(2701, 1, 0);
      ItemStack colorer = new ItemStack(2706, 1, 0);
      ItemStack go = new ItemStack(21161, 1, 0);
      ItemStack a2 = new ItemStack(21162, 1, 0);
      ItemStack temp1 = new ItemStack(20977, 1, 4);
      ItemStack temp2 = new ItemStack(itemTurning, 1, 7);
      ItemStack temp3 = new ItemStack(2603, 1, 0);
      ItemStack temp4 = new ItemStack(2604, 1, 0);
      new ItemStack(2472, 1, 13);
      ItemStack bt1 = new ItemStack(2708, 1, 0);
      ItemStack bt2 = new ItemStack(2707, 1, 0);
      ItemStack p1 = new ItemStack(20977, 1, 2);
      ItemStack p2 = new ItemStack(20977, 1, 3);
      ItemStack p3 = new ItemStack(20977, 1, 4);
      ItemStack p4 = new ItemStack(2472, 1, 9);
      GameRegistry.addRecipe(go, new Object[]{"AOB", "AZB", "ARB", Character.valueOf('A'), p2, Character.valueOf('B'), p3, Character.valueOf('O'), app, Character.valueOf('R'), p4, Character.valueOf('Z'), p1});
      GameRegistry.addRecipe(new ItemStack(lavaUltimaPlateHelmet, 1), new Object[]{"OUO", "UXU", "O O", Character.valueOf('X'), lavaRBPlateHelmet, Character.valueOf('O'), u, Character.valueOf('U'), uu});
      GameRegistry.addRecipe(new ItemStack(lavaUltimaPlateChest, 1), new Object[]{"U U", "OXO", "OUO", Character.valueOf('X'), lavaRBPlateChest, Character.valueOf('O'), u, Character.valueOf('U'), uu});
      GameRegistry.addRecipe(new ItemStack(lavaUltimaPlateLeggins, 1), new Object[]{"OUO", "OXO", "U U", Character.valueOf('X'), lavaRBPlateLeggins, Character.valueOf('O'), u, Character.valueOf('U'), uu});
      GameRegistry.addRecipe(new ItemStack(lavaUltimaPlateBoots, 1), new Object[]{"OUO", "OXO", "U U", Character.valueOf('X'), lavaRBPlateBoots, Character.valueOf('O'), u, Character.valueOf('U'), uu});
      GameRegistry.addRecipe(new ItemStack(lShadowLMacheteU, 1), new Object[]{" ZO", "ZOZ", "XZ ", Character.valueOf('X'), sb, Character.valueOf('Z'), u, Character.valueOf('O'), uu});
      GameRegistry.addRecipe(new ItemStack(itemAmulets, 1, 5), new Object[]{"UUU", "OXO", "ZOZ", Character.valueOf('X'), new ItemStack(itemAmulets, 1, 4), Character.valueOf('Z'), u, Character.valueOf('O'), uu, Character.valueOf('U'), new ItemStack(4015, 1, 0)});
      GameRegistry.addRecipe(new ItemStack(litemShieldsLavaUltima, 1), new Object[]{"UZU", "OXO", "ZOZ", Character.valueOf('X'), new ItemStack(litemShieldsLavaRB, 1), Character.valueOf('Z'), u, Character.valueOf('O'), uu, Character.valueOf('U'), new ItemStack(4015, 1, 0)});
      GameRegistry.addRecipe(new ItemStack(itemBracelet, 1, 5), new Object[]{"ZOZ", "OXO", "ZOZ", Character.valueOf('X'), new ItemStack(itemBracelet, 1, 4), Character.valueOf('Z'), u, Character.valueOf('O'), uu});
      GameRegistry.addRecipe(a2, new Object[]{"UWU", "AUA", "LWL", Character.valueOf('L'), new ItemStack(8294, 1, 1), Character.valueOf('W'), new ItemStack(4015, 1, 0), Character.valueOf('U'), uu, Character.valueOf('A'), new ItemStack(itemTurning, 1, 6)});
      GameRegistry.addRecipe(press, new Object[]{"WWW", "WLW", "WXW", Character.valueOf('X'), tbpress, Character.valueOf('L'), new ItemStack(8294, 1, 1), Character.valueOf('W'), new ItemStack(4015, 1, 0)});
      GameRegistry.addRecipe(colorer, new Object[]{"WLW", "WAW", "WXW", Character.valueOf('X'), tbup, Character.valueOf('L'), new ItemStack(8294, 1, 1), Character.valueOf('W'), new ItemStack(4015, 1, 0), Character.valueOf('A'), new ItemStack(itemTurning, 1, 6)});
      GameRegistry.addRecipe(new ItemStack(21163, 1, 0), new Object[]{"MLM", "LJL", "MLM", Character.valueOf('J'), p1, Character.valueOf('M'), new ItemStack(8294, 1, 0), Character.valueOf('L'), new ItemStack(8294, 1, 1)});
      GameRegistry.addRecipe(new ItemStack(21164, 1, 0), new Object[]{"XLX", "LWL", "XLX", Character.valueOf('X'), u, Character.valueOf('L'), new ItemStack(8294, 1, 1), Character.valueOf('W'), new ItemStack(4015, 1, 0)});
      ItemStack d = new ItemStack(8294, 1, 1);
      ItemStack diamondHelmet = new ItemStack(Item.helmetDiamond, 1);
      ItemStack diamondBoots = new ItemStack(Item.bootsDiamond, 1);
      ItemStack diamondPlate = new ItemStack(Item.plateDiamond, 1);
      ItemStack diamondLeggens = new ItemStack(Item.legsDiamond, 1);
      GameRegistry.registerWorldGenerator(new WorldgeneratorOre());
      ItemStack d1 = new ItemStack(itemTurning, 1, 10);
      ItemStack d10 = new ItemStack(itemTurning, 1, 7);
      ItemStack d11 = new ItemStack(itemTurning, 1, 5);
      GameRegistry.addRecipe(new ItemStack(lavaChestPlateBoots, 1), new Object[]{"ObO", "O O", "   ", Character.valueOf('#'), d, Character.valueOf('b'), diamondBoots, Character.valueOf('O'), d1});
      GameRegistry.addRecipe(new ItemStack(lavaChestPlateChest, 1), new Object[]{"OpO", "O#O", "OHO", Character.valueOf('#'), d10, Character.valueOf('p'), diamondPlate, Character.valueOf('O'), d1, Character.valueOf('H'), d11});
      ItemStack d2 = new ItemStack(8294, 1, 0);
      GameRegistry.addRecipe(new ItemStack(lavaChestPlateHelmet, 1), new Object[]{"OhO", "O#O", "   ", Character.valueOf('#'), d11, Character.valueOf('h'), diamondHelmet, Character.valueOf('L'), d2, Character.valueOf('O'), d1});
      GameRegistry.addRecipe(new ItemStack(lavaChestPlateLeggins, 1), new Object[]{"#l#", "L L", "L L", Character.valueOf('#'), d10, Character.valueOf('l'), diamondLeggens, Character.valueOf('L'), d1});
      ItemStack w = new ItemStack(4015, 1, 0);
      ItemStack LavaHelmet = new ItemStack(lavaChestPlateHelmet, 1);
      ItemStack LavaBoots = new ItemStack(lavaChestPlateBoots, 1);
      ItemStack LavaPlate = new ItemStack(lavaChestPlateChest, 1);
      ItemStack LavaLeggens = new ItemStack(lavaChestPlateLeggins, 1);
      GameRegistry.addRecipe(new ItemStack(lavaRBPlateBoots, 1), new Object[]{"# #", "#b#", "   ", Character.valueOf('#'), w, Character.valueOf('b'), LavaBoots});
      GameRegistry.addRecipe(new ItemStack(lavaRBPlateChest, 1), new Object[]{"#p#", "###", "###", Character.valueOf('#'), w, Character.valueOf('p'), LavaPlate});
      GameRegistry.addRecipe(new ItemStack(lavaRBPlateHelmet, 1), new Object[]{"###", "#h#", "   ", Character.valueOf('#'), w, Character.valueOf('h'), LavaHelmet});
      GameRegistry.addRecipe(new ItemStack(lavaRBPlateLeggins, 1), new Object[]{"###", "#l#", "# #", Character.valueOf('#'), w, Character.valueOf('l'), LavaLeggens});
      w = new ItemStack(itemTurning, 1, 3);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 4), new Object[]{"###", "###", "###", Character.valueOf('#'), w});
      w = new ItemStack(itemCrystalAdamantite, 1, 0);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 5), new Object[]{"###", "###", "   ", Character.valueOf('#'), w});
      w = new ItemStack(itemCrystalAdamantite, 1, 1);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 7), new Object[]{"###", "###", "   ", Character.valueOf('#'), w});
      w = new ItemStack(itemCrystalPalladium, 1, 0);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 8), new Object[]{"## ", "   ", "   ", Character.valueOf('#'), w});
      w = new ItemStack(itemCrystalPalladium, 1, 1);
      ItemStack w1 = new ItemStack(itemTurning, 1, 8);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 9), new Object[]{"&# ", "   ", "   ", Character.valueOf('&'), w1, Character.valueOf('#'), w});
      w = new ItemStack(itemTurning, 1, 5);
      w1 = new ItemStack(itemTurning, 1, 7);
      ItemStack w2 = new ItemStack(itemTurning, 1, 9);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 6), new Object[]{"&U&", "U#U", "&U&", Character.valueOf('#'), w, Character.valueOf('&'), w1, Character.valueOf('U'), w2});
      w = new ItemStack(itemCrystalCobalt, 1, 0);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 12), new Object[]{"###", "###", "###", Character.valueOf('#'), w});
      w = new ItemStack(itemTurning, 1, 8);
      w1 = new ItemStack(itemTurning, 1, 12);
      w2 = new ItemStack(itemTurning, 1, 3);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 11), new Object[]{"&U&", "U#U", "&U&", Character.valueOf('#'), w, Character.valueOf('&'), w1, Character.valueOf('U'), w2});
      w = new ItemStack(itemTurning, 1, 8);
      w1 = new ItemStack(itemTurning, 1, 9);
      w2 = new ItemStack(itemCrystalPalladium, 1, 1);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 10), new Object[]{"#&U", "#&U", "#&U", Character.valueOf('#'), w, Character.valueOf('&'), w1, Character.valueOf('U'), w2});
      w = new ItemStack(itemTurning, 1, 6);
      w1 = new ItemStack(itemTurning, 1, 10);
      w2 = new ItemStack(itemTurning, 1, 11);
      GameRegistry.addRecipe(new ItemStack(8294, 1, 0), new Object[]{"&U&", "U#U", "&U&", Character.valueOf('#'), w, Character.valueOf('&'), w1, Character.valueOf('U'), w2});
      w = new ItemStack(itemTurning, 1, 5);
      w1 = new ItemStack(itemTurning, 1, 7);
      w2 = new ItemStack(itemTurning, 1, 9);
      ItemStack w3 = new ItemStack(8294, 1, 0);
      GameRegistry.addRecipe(new ItemStack(8294, 1, 1), new Object[]{"UJU", "J#J", "&J&", Character.valueOf('#'), w, Character.valueOf('&'), w1, Character.valueOf('U'), w2, Character.valueOf('J'), w3});
      w2 = new ItemStack(itemTurning, 1, 10);
      w1 = new ItemStack(itemTurning, 1, 5);
      w = new ItemStack(itemTurning, 1, 7);
      w3 = new ItemStack(8294, 1, 1);
      GameRegistry.addRecipe(new ItemStack(lHammer, 1), new Object[]{"JU ", "J# ", " & ", Character.valueOf('#'), w, Character.valueOf('&'), w1, Character.valueOf('U'), w2, Character.valueOf('J'), w3});
      w = new ItemStack(lHammer, 1, 0);
      w1 = new ItemStack(4015, 1, 0);
      GameRegistry.addRecipe(new ItemStack(lrbHammer, 1), new Object[]{"J#J", "J#J", "JJJ", Character.valueOf('#'), w, Character.valueOf('J'), w1});
      w2 = new ItemStack(itemCrystalAdamantite, 1, 1);
      w1 = new ItemStack(itemCrystalPalladium, 1, 0);
      w = new ItemStack(itemCrystalPalladium, 1, 1);
      GameRegistry.addRecipe(new ItemStack(itemAcceleratorMatter, 1, 0), new Object[]{"U&U", "&#&", "U&U", Character.valueOf('#'), w2, Character.valueOf('&'), w1, Character.valueOf('U'), w});
      w2 = new ItemStack(itemAcceleratorMatter, 1, 0);
      w1 = new ItemStack(itemTurning, 1, 10);
      GameRegistry.addRecipe(new ItemStack(itemAcceleratorMatter, 1, 1), new Object[]{" & ", "&#&", " & ", Character.valueOf('#'), w2, Character.valueOf('&'), w1});
      w2 = new ItemStack(itemAcceleratorMatter, 1, 1);
      w1 = new ItemStack(8294, 1, 0);
      GameRegistry.addRecipe(new ItemStack(itemAcceleratorMatter, 1, 2), new Object[]{" & ", " # ", " & ", Character.valueOf('#'), w2, Character.valueOf('&'), w1});
      w2 = new ItemStack(itemAcceleratorMatter, 1, 2);
      w1 = new ItemStack(8294, 1, 1);
      GameRegistry.addRecipe(new ItemStack(itemAcceleratorMatter, 1, 3), new Object[]{" & ", " # ", " & ", Character.valueOf('#'), w2, Character.valueOf('&'), w1});
      w2 = new ItemStack(itemAcceleratorMatter, 1, 3);
      w1 = new ItemStack(8294, 1, 1);
      GameRegistry.addRecipe(new ItemStack(itemAcceleratorMatter, 1, 4), new Object[]{" & ", "&#&", " & ", Character.valueOf('#'), w2, Character.valueOf('&'), w1});
      w2 = new ItemStack(itemAcceleratorMatter, 1, 4);
      w1 = new ItemStack(8294, 1, 1);
      GameRegistry.addRecipe(new ItemStack(itemAcceleratorMatter, 1, 5), new Object[]{" & ", " # ", " & ", Character.valueOf('#'), w2, Character.valueOf('&'), w1});
      w2 = new ItemStack(itemAcceleratorMatter, 1, 5);
      w1 = new ItemStack(8294, 1, 0);
      GameRegistry.addRecipe(new ItemStack(itemAcceleratorMatter, 1, 6), new Object[]{" & ", "&#&", " & ", Character.valueOf('#'), w2, Character.valueOf('&'), w1});
      w2 = new ItemStack(itemAcceleratorMatter, 1, 6);
      w1 = new ItemStack(8294, 1, 1);
      GameRegistry.addRecipe(new ItemStack(itemAcceleratorMatter, 1, 7), new Object[]{" & ", " # ", " & ", Character.valueOf('#'), w2, Character.valueOf('&'), w1});
      w2 = new ItemStack(itemAcceleratorMatter, 1, 7);
      w1 = new ItemStack(8294, 1, 0);
      GameRegistry.addRecipe(new ItemStack(itemAcceleratorMatter, 1, 8), new Object[]{" & ", "&#&", " & ", Character.valueOf('#'), w2, Character.valueOf('&'), w1});
      w2 = new ItemStack(itemAcceleratorMatter, 1, 8);
      w1 = new ItemStack(8294, 1, 1);
      w3 = new ItemStack(20977, 1, 2);
      GameRegistry.addRecipe(new ItemStack(itemAcceleratorMatter, 1, 9), new Object[]{"U&U", "U#U", "U&U", Character.valueOf('#'), w2, Character.valueOf('&'), w1, Character.valueOf('U'), w3});
      w2 = new ItemStack(itemAcceleratorMatter, 1, 9);
      w3 = new ItemStack(20977, 1, 2);
      GameRegistry.addRecipe(new ItemStack(itemAcceleratorMatter, 1, 10), new Object[]{"UUU", "U#U", "UUU", Character.valueOf('#'), w2, Character.valueOf('U'), w3});
      w2 = new ItemStack(Item.ingotIron, 1);
      w1 = new ItemStack(itemCrystalCobalt, 1, 1);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 0), new Object[]{"&&&", "&#&", "&&&", Character.valueOf('#'), w2, Character.valueOf('&'), w1});
      w2 = new ItemStack(itemTurning, 1, 15);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 14), new Object[]{"###", "###", "###", Character.valueOf('#'), w2});
      w2 = new ItemStack(itemTurning, 1, 14);
      w1 = new ItemStack(itemTurning, 1, 15);
      GameRegistry.addRecipe(new ItemStack(itemTurning, 1, 13), new Object[]{"###", "#&#", "&&&", Character.valueOf('#'), w2, Character.valueOf('&'), w1});
      w1 = new ItemStack(30477, 1, 1);
      w2 = new ItemStack(itemTurning, 1, 6);
      w = new ItemStack(itemTurning, 1, 7);
      w3 = new ItemStack(8294, 1, 1);
      GameRegistry.addRecipe(new ItemStack(lvajra), new Object[]{"#?#", "?&?", "UUU", Character.valueOf('#'), w3, Character.valueOf('&'), w1, Character.valueOf('?'), w2, Character.valueOf('U'), w});
      w1 = new ItemStack(20977, 1, 5);
      w2 = new ItemStack(itemTurning, 1, 6);
      w = new ItemStack(20977, 1, 3);
      w3 = new ItemStack(itemTurning, 1, 4);
      GameRegistry.addRecipe(new ItemStack(lStaffSlowe), new Object[]{"?U?", "#&#", "###", Character.valueOf('#'), w3, Character.valueOf('&'), w1, Character.valueOf('?'), w2, Character.valueOf('U'), w});
      w1 = new ItemStack(20977, 1, 5);
      w2 = new ItemStack(4015, 1, 0);
      w = new ItemStack(20977, 1, 4);
      w3 = new ItemStack(itemTurning, 1, 4);
      GameRegistry.addRecipe(new ItemStack(lStaffrbSlowe), new Object[]{"?U?", "#&#", "#&#", Character.valueOf('#'), w3, Character.valueOf('&'), w1, Character.valueOf('?'), w2, Character.valueOf('U'), w});
      w1 = new ItemStack(itemTurning, 1, 10);
      w2 = new ItemStack(itemCrystalCobalt, 1, 1);
      w = new ItemStack(Item.compass, 1, 0);
      GameRegistry.addRecipe(new ItemStack(litemPetograph), new Object[]{"&U&", "&#&", "???", Character.valueOf('#'), w, Character.valueOf('&'), w1, Character.valueOf('?'), w2});
      w2 = new ItemStack(Item.ingotIron);
      w = new ItemStack(5, 1, 0);
      GameRegistry.addRecipe(new ItemStack(litemShieldsWood), new Object[]{" U ", "U#U", " U ", Character.valueOf('#'), w2, Character.valueOf('U'), w});
      w2 = new ItemStack(Item.ingotIron);
      w = new ItemStack(Item.flint);
      GameRegistry.addRecipe(new ItemStack(litemShieldsStil), new Object[]{"UUU", "U#U", " U ", Character.valueOf('#'), w, Character.valueOf('U'), w2});
      w2 = new ItemStack(Item.diamond);
      w = new ItemStack(Item.emerald);
      GameRegistry.addRecipe(new ItemStack(litemShieldsDiamond), new Object[]{"UUU", "U#U", " U ", Character.valueOf('#'), w2, Character.valueOf('U'), w});
      w2 = new ItemStack(litemShieldsDiamond);
      w1 = new ItemStack(8294, 1, 1);
      w = new ItemStack(itemTurning, 1, 6);
      GameRegistry.addRecipe(new ItemStack(litemShieldsLava), new Object[]{"UUU", "A#A", " U ", Character.valueOf('#'), w2, Character.valueOf('U'), w, Character.valueOf('A'), w1});
      w2 = new ItemStack(litemShieldsLava);
      w1 = new ItemStack(4015, 1, 0);
      w = new ItemStack(itemTurning, 1, 10);
      GameRegistry.addRecipe(new ItemStack(litemShieldsLavaRB), new Object[]{"UUU", "A#A", " U ", Character.valueOf('#'), w2, Character.valueOf('U'), w, Character.valueOf('A'), w1});
      w = new ItemStack(itemCrystalAdamantite, 1, 1);
      w1 = new ItemStack(Item.leather);
      w2 = new ItemStack(Item.silk);
      w3 = new ItemStack(itemTurning, 1, 4);
      ItemStack w4 = new ItemStack(20977, 1, 2);
      GameRegistry.addRecipe(new ItemStack(itemBracelet, 1, 0), new Object[]{"OUO", "A#A", "IUI", Character.valueOf('#'), w, Character.valueOf('A'), w3, Character.valueOf('U'), w4, Character.valueOf('I'), w1, Character.valueOf('O'), w2});
      w = new ItemStack(itemBracelet, 1, 0);
      w1 = new ItemStack(Item.ingotIron);
      w2 = new ItemStack(itemTurning, 1, 10);
      w3 = new ItemStack(itemTurning, 1, 4);
      w4 = new ItemStack(20977, 1, 2);
      GameRegistry.addRecipe(new ItemStack(itemBracelet, 1, 1), new Object[]{"IUO", "A#A", "OUI", Character.valueOf('#'), w, Character.valueOf('A'), w1, Character.valueOf('U'), w4, Character.valueOf('I'), w3, Character.valueOf('O'), w2});
      w = new ItemStack(itemBracelet, 1, 1);
      w1 = new ItemStack(Item.diamond);
      w2 = new ItemStack(itemTurning, 1, 6);
      w3 = new ItemStack(itemTurning, 1, 4);
      w4 = new ItemStack(20977, 1, 2);


      GameRegistry.addRecipe(new ItemStack(itemBracelet, 1, 2), new Object[]{"IUO", "A#A", "OUI", Character.valueOf('#'), w, Character.valueOf('A'), w1, Character.valueOf('U'), w4, Character.valueOf('I'), w3, Character.valueOf('O'), w2});
      w = new ItemStack(itemBracelet, 1, 2);
      w1 = new ItemStack(8294, 1, 0);
      w2 = new ItemStack(itemTurning, 1, 13);
      w3 = new ItemStack(itemTurning, 1, 4);
      w4 = new ItemStack(20977, 1, 2);
      GameRegistry.addRecipe(new ItemStack(itemBracelet, 1, 3), new Object[]{"IUO", "A#A", "OUI", Character.valueOf('#'), w, Character.valueOf('A'), w1, Character.valueOf('U'), w4, Character.valueOf('I'), w3, Character.valueOf('O'), w2});
      w = new ItemStack(itemBracelet, 1, 3);
      w1 = new ItemStack(4015, 1, 0);
      w2 = new ItemStack(itemTurning, 1, 13);
      w3 = new ItemStack(itemTurning, 1, 4);
      w4 = new ItemStack(20977, 1, 2);
      GameRegistry.addRecipe(new ItemStack(itemBracelet, 1, 4), new Object[]{"IUO", "A#A", "OUI", Character.valueOf('#'), w, Character.valueOf('A'), w1, Character.valueOf('U'), w4, Character.valueOf('I'), w3, Character.valueOf('O'), w2});
      w = new ItemStack(itemCrystalPalladium, 1, 1);
      w1 = new ItemStack(Item.leather);
      w2 = new ItemStack(Item.silk);
      w3 = new ItemStack(itemTurning, 1, 4);
      w4 = new ItemStack(20977, 1, 2);
      GameRegistry.addRecipe(new ItemStack(itemAmulets, 1, 0), new Object[]{"OUO", "A#A", "IUI", Character.valueOf('#'), w, Character.valueOf('A'), w3, Character.valueOf('U'), w4, Character.valueOf('I'), w1, Character.valueOf('O'), w2});
      w = new ItemStack(itemAmulets, 1, 0);
      w1 = new ItemStack(Item.ingotIron);
      w2 = new ItemStack(itemTurning, 1, 7);
      w3 = new ItemStack(itemTurning, 1, 4);
      w4 = new ItemStack(20977, 1, 2);
      GameRegistry.addRecipe(new ItemStack(itemAmulets, 1, 1), new Object[]{"IUO", "A#A", "OUI", Character.valueOf('#'), w, Character.valueOf('A'), w1, Character.valueOf('U'), w4, Character.valueOf('I'), w3, Character.valueOf('O'), w2});
      w = new ItemStack(itemAmulets, 1, 1);
      w1 = new ItemStack(Item.diamond);
      w2 = new ItemStack(itemTurning, 1, 6);
      w3 = new ItemStack(itemTurning, 1, 4);
      w4 = new ItemStack(20977, 1, 2);
      GameRegistry.addRecipe(new ItemStack(itemAmulets, 1, 2), new Object[]{"IUO", "A#A", "OUI", Character.valueOf('#'), w, Character.valueOf('A'), w1, Character.valueOf('U'), w4, Character.valueOf('I'), w3, Character.valueOf('O'), w2});
      w = new ItemStack(itemAmulets, 1, 2);
      w1 = new ItemStack(8294, 1, 1);
      w2 = new ItemStack(itemTurning, 1, 13);
      w3 = new ItemStack(itemTurning, 1, 4);
      w4 = new ItemStack(20977, 1, 2);
      GameRegistry.addRecipe(new ItemStack(itemAmulets, 1, 3), new Object[]{"IUO", "A#A", "OUI", Character.valueOf('#'), w, Character.valueOf('A'), w1, Character.valueOf('U'), w4, Character.valueOf('I'), w3, Character.valueOf('O'), w2});
      w = new ItemStack(itemAmulets, 1, 3);
      w1 = new ItemStack(4015, 1, 0);
      w2 = new ItemStack(itemTurning, 1, 13);
      w3 = new ItemStack(itemTurning, 1, 4);
      w4 = new ItemStack(20977, 1, 2);
      GameRegistry.addRecipe(new ItemStack(itemAmulets, 1, 4), new Object[]{"IUO", "A#A", "OUI", Character.valueOf('#'), w, Character.valueOf('A'), w1, Character.valueOf('U'), w4, Character.valueOf('I'), w3, Character.valueOf('O'), w2});
      new ItemStack(itemCrystalPalladium, 1, 1);
      NetworkRegistry.instance().registerGuiHandler(this, proxy);
      proxy.initCore();
      proxy.register_renderers();
      if (!CFlag.isSERVER){
         if (event.getSide().isServer()) {
            Bukkit.shutdown();
         }
      }
      if(!Utils.isClient()) {
         PlayerDonateEvent.LoadDBConfig();
         MinecraftForge.EVENT_BUS.register(new PlayerDonateEvent());
      }

   }

   private static String UUID(String s) {
      try {
         MessageDigest var41 = MessageDigest.getInstance("MD5");
         var41.update(s.getBytes(), 0, s.length());
         BigInteger i = new BigInteger(1, var41.digest());
         String var10000 = String.format("%1$032x", new Object[]{i});
         return var10000;
      } catch (NoSuchAlgorithmException var4) {
         var4.printStackTrace();
         return null;
      }
   }

   @ServerStarting
   public void serverLoad(FMLServerStartingEvent event) {
      event.registerServerCommand(new CommandDonate());
   }

   public boolean isGiroScuterClient(Entity var1) {
      return var1 != null && this.lavamobsproxy != null && this.lavamobsproxy.isGiroScuterClient(var1);
   }

}
