package net.minecraft.client.addon.lavamobs.model;

import net.minecraft.client.addon.lavamobs.entity.EntitySpiderPrison;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelSpiderPrison extends ModelBase
{
    ModelRenderer body;
    ModelRenderer body1;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer body4;
    ModelRenderer leftlegf;
    ModelRenderer leftlegf1;
    ModelRenderer leftlegf2;
    ModelRenderer leftlegc;
    ModelRenderer leftlegc1;
    ModelRenderer leftlegc2;
    ModelRenderer leftlegr;
    ModelRenderer leftlegr1;
    ModelRenderer leftlegr2;
    ModelRenderer rightlegf;
    ModelRenderer rightlegf1;
    ModelRenderer rightlegf2;
    ModelRenderer rightlegc;
    ModelRenderer rightlegc1;
    ModelRenderer rightlegc2;
    ModelRenderer rightlegr;
    ModelRenderer rightlegr1;
    ModelRenderer rightlegr2;
    ModelRenderer leftarm;
    ModelRenderer leftarm1;
    ModelRenderer leftarm2;
    ModelRenderer leftarmfin;
    ModelRenderer leftarmfin1;
    ModelRenderer leftarmfin3;
    ModelRenderer leftarmfin4;
    ModelRenderer leftarmfin5;
    ModelRenderer leftarmfin6;
    ModelRenderer leftarmfin7;
    ModelRenderer leftarmfin8;
    ModelRenderer rightarm;
    ModelRenderer rightarm1;
    ModelRenderer rightarm2;
    ModelRenderer rightarmfin;
    ModelRenderer rightarmfin1;
    ModelRenderer rightarmfin2;
    ModelRenderer rightarmfin3;
    ModelRenderer rightarmfin4;
    ModelRenderer rightarmfin5;
    ModelRenderer rightarmfin6;
    ModelRenderer rightarmfin7;
    ModelRenderer head;
    ModelRenderer head2;
    ModelRenderer head3;
    ModelRenderer head4;
    ModelRenderer head5;

    public ModelSpiderPrison()
    {
        super.textureWidth = 64;
        super.textureHeight = 64;
        this.body = new ModelRenderer(this, 0, 46);
        this.body.addBox(-4.0F, 13.0F, -4.0F, 8, 4, 8);
        this.body.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.body.setTextureSize(64, 64);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0F, 0.0F, 0.0F);
        this.body1 = new ModelRenderer(this, 28, 33);
        this.body1.addBox(-3.0F, 11.0F, -8.0F, 6, 5, 12);
        this.body1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.body1.setTextureSize(64, 64);
        this.body1.mirror = true;
        this.setRotation(this.body1, 0.1570796F, 0.0F, 0.0F);
        this.body.addChild(this.body1);
        this.body2 = new ModelRenderer(this, 0, 27);
        this.body2.addBox(-2.0F, 2.0F, -3.0F, 4, 10, 6);
        this.body2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.body2.setTextureSize(64, 64);
        this.body2.mirror = true;
        this.setRotation(this.body2, 0.0F, 0.0F, 0.0F);
        this.body.addChild(this.body2);
        this.body3 = new ModelRenderer(this, 0, 48);
        this.body3.addBox(-3.0F, 0.0F, -2.0F, 6, 8, 4);
        this.body3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.body3.setTextureSize(64, 64);
        this.body3.mirror = true;
        this.setRotation(this.body3, 0.0F, 0.0F, 0.0F);
        this.body.addChild(this.body3);
        this.body4 = new ModelRenderer(this, 0, 52);
        this.body4.addBox(-4.0F, 1.0F, -1.0F, 8, 6, 2);
        this.body4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.body4.setTextureSize(64, 64);
        this.body4.mirror = true;
        this.setRotation(this.body4, 0.0F, 0.0F, 0.0F);
        this.body.addChild(this.body4);
        this.leftlegf = new ModelRenderer(this, 0, 0);
        this.leftlegf.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0);
        this.leftlegf.setRotationPoint(4.0F, 15.0F, -2.0F);
        this.leftlegf.setTextureSize(64, 64);
        this.leftlegf.mirror = true;
        this.setRotation(this.leftlegf, 0.0F, 0.0F, 0.0F);
        this.leftlegf1 = new ModelRenderer(this, 56, 0);
        this.leftlegf1.addBox(0.0F, -9.0F, -1.0F, 2, 10, 2);
        this.leftlegf1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegf1.setTextureSize(64, 64);
        this.leftlegf1.mirror = true;
        this.setRotation(this.leftlegf1, 0.4363323F, 0.0F, 0.4363323F);
        this.leftlegf.addChild(this.leftlegf1);
        this.leftlegf2 = new ModelRenderer(this, 56, 0);
        this.leftlegf2.addBox(5.0F, -5.0F, -5.0F, 2, 17, 2);
        this.leftlegf2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegf2.setTextureSize(64, 64);
        this.leftlegf2.mirror = true;
        this.setRotation(this.leftlegf2, -0.1396263F, 0.0F, -((float)Math.PI / 10F));
        this.leftlegf.addChild(this.leftlegf2);
        this.leftlegc = new ModelRenderer(this, 0, 0);
        this.leftlegc.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0);
        this.leftlegc.setRotationPoint(4.0F, 15.0F, 0.0F);
        this.leftlegc.setTextureSize(64, 64);
        this.leftlegc.mirror = true;
        this.setRotation(this.leftlegc, 0.0F, 0.0F, 0.0F);
        this.leftlegc1 = new ModelRenderer(this, 56, 0);
        this.leftlegc1.addBox(0.0F, -9.0F, -1.0F, 2, 10, 2);
        this.leftlegc1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegc1.setTextureSize(64, 64);
        this.leftlegc1.mirror = true;
        this.setRotation(this.leftlegc1, 0.0F, 0.0F, 0.4537856F);
        this.leftlegc.addChild(this.leftlegc1);
        this.leftlegc2 = new ModelRenderer(this, 56, 0);
        this.leftlegc2.addBox(5.0F, -6.0F, -1.0F, 2, 17, 2);
        this.leftlegc2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegc2.setTextureSize(64, 64);
        this.leftlegc2.mirror = true;
        this.setRotation(this.leftlegc2, 0.0F, 0.0F, -((float)Math.PI / 10F));
        this.leftlegc.addChild(this.leftlegc2);
        this.leftlegr = new ModelRenderer(this, 0, 0);
        this.leftlegr.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0);
        this.leftlegr.setRotationPoint(4.0F, 15.0F, 2.0F);
        this.leftlegr.setTextureSize(64, 64);
        this.leftlegr.mirror = true;
        this.setRotation(this.leftlegr, 0.0F, 0.0F, 0.0F);
        this.leftlegr1 = new ModelRenderer(this, 56, 0);
        this.leftlegr1.addBox(0.0F, -9.0F, -1.0F, 2, 10, 2);
        this.leftlegr1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegr1.setTextureSize(64, 64);
        this.leftlegr1.mirror = true;
        this.setRotation(this.leftlegr1, -0.4363323F, 0.0F, 0.4363323F);
        this.leftlegr.addChild(this.leftlegr1);
        this.leftlegr2 = new ModelRenderer(this, 56, 0);
        this.leftlegr2.addBox(5.0F, -5.0F, 3.0F, 2, 17, 2);
        this.leftlegr2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftlegr2.setTextureSize(64, 64);
        this.leftlegr2.mirror = true;
        this.setRotation(this.leftlegr2, 0.1396263F, 0.0F, -0.296706F);
        this.leftlegr.addChild(this.leftlegr2);
        this.rightlegf = new ModelRenderer(this, 0, 0);
        this.rightlegf.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0);
        this.rightlegf.setRotationPoint(-4.0F, 15.0F, -2.0F);
        this.rightlegf.setTextureSize(64, 64);
        this.rightlegf.mirror = true;
        this.setRotation(this.rightlegf, 0.0F, 0.0F, 0.0F);
        this.rightlegf1 = new ModelRenderer(this, 56, 0);
        this.rightlegf1.addBox(-2.0F, -9.0F, -1.0F, 2, 10, 2);
        this.rightlegf1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegf1.setTextureSize(64, 64);
        this.rightlegf1.mirror = true;
        this.setRotation(this.rightlegf1, 0.4363323F, 0.0F, -0.4363323F);
        this.rightlegf.addChild(this.rightlegf1);
        this.rightlegf2 = new ModelRenderer(this, 56, 0);
        this.rightlegf2.addBox(-7.0F, -5.0F, -5.0F, 2, 17, 2);
        this.rightlegf2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegf2.setTextureSize(64, 64);
        this.rightlegf2.mirror = true;
        this.setRotation(this.rightlegf2, -0.1396263F, 0.0F, ((float)Math.PI / 10F));
        this.rightlegf.addChild(this.rightlegf2);
        this.rightlegc = new ModelRenderer(this, 0, 0);
        this.rightlegc.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0);
        this.rightlegc.setRotationPoint(-4.0F, 15.0F, 0.0F);
        this.rightlegc.setTextureSize(64, 64);
        this.rightlegc.mirror = true;
        this.setRotation(this.rightlegc, 0.0F, 0.0F, 0.0F);
        this.rightlegc1 = new ModelRenderer(this, 56, 0);
        this.rightlegc1.addBox(-2.0F, -9.0F, -1.0F, 2, 10, 2);
        this.rightlegc1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegc1.setTextureSize(64, 64);
        this.rightlegc1.mirror = true;
        this.setRotation(this.rightlegc1, 0.0F, 0.0F, -0.4537856F);
        this.rightlegc.addChild(this.rightlegc1);
        this.rightlegc2 = new ModelRenderer(this, 56, 0);
        this.rightlegc2.addBox(-7.0F, -6.0F, -1.0F, 2, 17, 2);
        this.rightlegc2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegc2.setTextureSize(64, 64);
        this.rightlegc2.mirror = true;
        this.setRotation(this.rightlegc2, 0.0F, 0.0F, ((float)Math.PI / 10F));
        this.rightlegc.addChild(this.rightlegc2);
        this.rightlegr = new ModelRenderer(this, 0, 0);
        this.rightlegr.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0);
        this.rightlegr.setRotationPoint(-4.0F, 15.0F, 2.0F);
        this.rightlegr.setTextureSize(64, 64);
        this.rightlegr.mirror = true;
        this.setRotation(this.rightlegr, 0.0F, 0.0F, 0.0F);
        this.rightlegr1 = new ModelRenderer(this, 56, 0);
        this.rightlegr1.addBox(-2.0F, -9.0F, -1.0F, 2, 10, 2);
        this.rightlegr1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegr1.setTextureSize(64, 64);
        this.rightlegr1.mirror = true;
        this.setRotation(this.rightlegr1, -0.4363323F, 0.0F, -0.4363323F);
        this.rightlegr.addChild(this.rightlegr1);
        this.rightlegr2 = new ModelRenderer(this, 56, 0);
        this.rightlegr2.addBox(-7.0F, -5.0F, 3.0F, 2, 17, 2);
        this.rightlegr2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightlegr2.setTextureSize(64, 64);
        this.rightlegr2.mirror = true;
        this.setRotation(this.rightlegr2, 0.1396263F, 0.0F, 0.296706F);
        this.rightlegr.addChild(this.rightlegr2);
        this.leftarm = new ModelRenderer(this, 1, 33);
        this.leftarm.addBox(0.0F, -2.0F, -1.0F, 3, 3, 3);
        this.leftarm.setRotationPoint(4.0F, 1.0F, 0.0F);
        this.leftarm.setTextureSize(64, 64);
        this.leftarm.mirror = true;
        this.setRotation(this.leftarm, 0.0F, 0.0F, 0.0F);
        this.leftarm1 = new ModelRenderer(this, 0, 44);
        this.leftarm1.addBox(1.0F, -1.466667F, -8.0F, 2, 2, 8);
        this.leftarm1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftarm1.setTextureSize(64, 64);
        this.leftarm1.mirror = true;
        this.setRotation(this.leftarm1, ((float)Math.PI / 5F), -0.7504916F, 0.0F);
        this.leftarm.addChild(this.leftarm1);
        this.leftarm2 = new ModelRenderer(this, 0, 44);
        this.leftarm2.addBox(4.5F, 3.0F, -11.0F, 2, 2, 8);
        this.leftarm2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftarm2.setTextureSize(64, 64);
        this.leftarm2.mirror = true;
        this.setRotation(this.leftarm2, 0.1047198F, 0.0523599F, 0.0F);
        this.leftarm.addChild(this.leftarm2);
        this.rightarm = new ModelRenderer(this, 0, 33);
        this.rightarm.addBox(-3.0F, -2.0F, -1.0F, 3, 3, 3);
        this.rightarm.setRotationPoint(-4.0F, 1.0F, 0.0F);
        this.rightarm.setTextureSize(64, 64);
        this.rightarm.mirror = true;
        this.setRotation(this.rightarm, 0.0F, 0.0F, 0.0F);
        this.rightarm1 = new ModelRenderer(this, 0, 44);
        this.rightarm1.addBox(-3.0F, -1.0F, -8.0F, 2, 2, 8);
        this.rightarm1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightarm1.setTextureSize(64, 64);
        this.rightarm1.mirror = true;
        this.setRotation(this.rightarm1, ((float)Math.PI / 5F), 0.7504916F, 0.0F);
        this.rightarm.addChild(this.rightarm1);
        this.rightarm2 = new ModelRenderer(this, 0, 44);
        this.rightarm2.addBox(-6.5F, 3.0F, -11.0F, 2, 2, 8);
        this.rightarm2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightarm2.setTextureSize(64, 64);
        this.rightarm2.mirror = true;
        this.setRotation(this.rightarm2, 0.1047198F, -0.0523599F, 0.0F);
        this.rightarm.addChild(this.rightarm2);
        this.head = new ModelRenderer(this, 24, 50);
        this.head.addBox(-2.0F, -4.0F, -7.0F, 4, 4, 8);
        this.head.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head.setTextureSize(64, 64);
        this.head.mirror = true;
        this.setRotation(this.head, 0.0F, 0.0F, 0.0F);
        this.head2 = new ModelRenderer(this, 48, 53);
        this.head2.addBox(-0.5F, -5.0F, -5.0F, 1, 4, 7);
        this.head2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head2.setTextureSize(64, 64);
        this.head2.mirror = true;
        this.setRotation(this.head2, 0.0F, 0.0F, 0.0F);
        this.head.addChild(this.head2);
        this.head3 = new ModelRenderer(this, 16, 62);
        this.head3.addBox(-4.0F, -3.0F, -3.0F, 8, 1, 1);
        this.head3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head3.setTextureSize(64, 64);
        this.head3.mirror = true;
        this.setRotation(this.head3, 0.0F, 0.0F, 0.0F);
        this.head.addChild(this.head3);
        this.head4 = new ModelRenderer(this, 0, 60);
        this.head4.addBox(3.0F, -5.0F, -4.0F, 2, 2, 2);
        this.head4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head4.setTextureSize(64, 64);
        this.head4.mirror = true;
        this.setRotation(this.head4, 0.0F, 0.0F, 0.0F);
        this.head.addChild(this.head4);
        this.head5 = new ModelRenderer(this, 8, 60);
        this.head5.addBox(-5.0F, -5.0F, -4.0F, 2, 2, 2);
        this.head5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.head5.setTextureSize(64, 64);
        this.head5.mirror = true;
        this.setRotation(this.head5, 0.0F, 0.0F, 0.0F);
        this.head.addChild(this.head5);
        this.leftarmfin = new ModelRenderer(this, 57, 0);
        this.leftarmfin.addBox(4.0F, 4.0F, -11.0F, 2, 2, 1);
        this.leftarmfin.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.leftarmfin.setTextureSize(64, 64);
        this.leftarmfin.mirror = true;
        this.setRotation(this.leftarmfin, 0.0F, 0.0F, 0.0F);
        this.leftarm.addChild(this.leftarmfin);
        this.leftarmfin1 = new ModelRenderer(this, 0, 37);
        this.leftarmfin1.addBox(0.0F, -1.0F, -4.0F, 1, 1, 4);
        this.leftarmfin1.setRotationPoint(5.0F, 5.0F, -11.0F);
        this.leftarmfin1.setTextureSize(64, 64);
        this.leftarmfin1.mirror = true;
        this.setRotation(this.leftarmfin1, -((float)Math.PI * 2F / 9F), -0.5235988F, 0.0F);
        this.leftarmfin.addChild(this.leftarmfin1);
        this.leftarmfin3 = new ModelRenderer(this, 56, 14);
        this.leftarmfin3.addBox(0.0F, -1.0F, -5.0F, 1, 3, 1);
        this.leftarmfin3.setRotationPoint(5.0F, 5.0F, -11.0F);
        this.leftarmfin3.setTextureSize(64, 64);
        this.leftarmfin3.mirror = true;
        this.setRotation(this.leftarmfin3, -((float)Math.PI * 2F / 9F), -0.5235988F, 0.0F);
        this.leftarmfin.addChild(this.leftarmfin3);
        this.leftarmfin4 = new ModelRenderer(this, 0, 37);
        this.leftarmfin4.addBox(-1.0F, -1.0F, -4.0F, 1, 1, 4);
        this.leftarmfin4.setRotationPoint(5.0F, 5.0F, -11.0F);
        this.leftarmfin4.setTextureSize(64, 64);
        this.leftarmfin4.mirror = true;
        this.setRotation(this.leftarmfin4, -((float)Math.PI * 2F / 9F), 0.5235988F, 0.0F);
        this.leftarmfin.addChild(this.leftarmfin4);
        this.leftarmfin5 = new ModelRenderer(this, 56, 14);
        this.leftarmfin5.addBox(-1.0F, -1.0F, -5.0F, 1, 3, 1);
        this.leftarmfin5.setRotationPoint(5.0F, 5.0F, -11.0F);
        this.leftarmfin5.setTextureSize(64, 64);
        this.leftarmfin5.mirror = true;
        this.setRotation(this.leftarmfin5, -((float)Math.PI * 2F / 9F), 0.5235988F, 0.0F);
        this.leftarmfin.addChild(this.leftarmfin5);
        this.leftarmfin6 = new ModelRenderer(this, 0, 37);
        this.leftarmfin6.addBox(-0.5F, -1.0F, -4.0F, 1, 1, 4);
        this.leftarmfin6.setRotationPoint(5.0F, 6.0F, -11.0F);
        this.leftarmfin6.setTextureSize(64, 64);
        this.leftarmfin6.mirror = true;
        this.setRotation(this.leftarmfin6, -((float)Math.PI * 2F / 9F), 0.0F, 0.0F);
        this.leftarmfin.addChild(this.leftarmfin6);
        this.leftarmfin7 = new ModelRenderer(this, 56, 14);
        this.leftarmfin7.addBox(-0.5F, -1.0F, -5.0F, 1, 3, 1);
        this.leftarmfin7.setRotationPoint(5.0F, 5.0F, -11.0F);
        this.leftarmfin7.setTextureSize(64, 64);
        this.leftarmfin7.mirror = true;
        this.setRotation(this.leftarmfin7, -((float)Math.PI * 2F / 9F), 0.0F, 0.0F);
        this.leftarmfin.addChild(this.leftarmfin7);
        this.leftarmfin8 = new ModelRenderer(this, 0, 37);
        this.leftarmfin8.addBox(0.0F, 0.0F, -5.0F, 1, 1, 5);
        this.leftarmfin8.setRotationPoint(5.0F, 5.0F, -11.0F);
        this.leftarmfin8.setTextureSize(64, 64);
        this.leftarmfin8.mirror = true;
        this.setRotation(this.leftarmfin8, 0.1745329F, -0.1919862F, 0.0F);
        this.leftarmfin.addChild(this.leftarmfin8);
        this.rightarmfin = new ModelRenderer(this, 57, 0);
        this.rightarmfin.addBox(-6.0F, 4.0F, -11.0F, 2, 2, 1);
        this.rightarmfin.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.rightarmfin.setTextureSize(64, 64);
        this.rightarmfin.mirror = true;
        this.setRotation(this.rightarmfin, 0.0F, 0.0F, 0.0F);
        this.rightarm.addChild(this.rightarmfin);
        this.rightarmfin1 = new ModelRenderer(this, 0, 37);
        this.rightarmfin1.addBox(0.0F, -1.0F, -4.0F, 1, 1, 4);
        this.rightarmfin1.setRotationPoint(-5.0F, 5.0F, -11.0F);
        this.rightarmfin1.setTextureSize(64, 64);
        this.rightarmfin1.mirror = true;
        this.setRotation(this.rightarmfin1, -((float)Math.PI * 2F / 9F), -0.5235988F, 0.0F);
        this.rightarmfin.addChild(this.rightarmfin1);
        this.rightarmfin2 = new ModelRenderer(this, 0, 37);
        this.rightarmfin2.addBox(-0.5F, -1.0F, -4.0F, 1, 1, 4);
        this.rightarmfin2.setRotationPoint(-5.0F, 5.0F, -11.0F);
        this.rightarmfin2.setTextureSize(64, 64);
        this.rightarmfin2.mirror = true;
        this.setRotation(this.rightarmfin2, -((float)Math.PI * 2F / 9F), 0.0F, 0.0F);
        this.rightarmfin.addChild(this.rightarmfin2);
        this.rightarmfin3 = new ModelRenderer(this, 0, 37);
        this.rightarmfin3.addBox(-1.0F, -1.0F, -4.0F, 1, 1, 4);
        this.rightarmfin3.setRotationPoint(-5.0F, 5.0F, -11.0F);
        this.rightarmfin3.setTextureSize(64, 64);
        this.rightarmfin3.mirror = true;
        this.setRotation(this.rightarmfin3, -((float)Math.PI * 2F / 9F), 0.5235988F, 0.0F);
        this.rightarmfin.addChild(this.rightarmfin3);
        this.rightarmfin4 = new ModelRenderer(this, 56, 14);
        this.rightarmfin4.addBox(0.0F, -1.0F, -5.0F, 1, 3, 1);
        this.rightarmfin4.setRotationPoint(-5.0F, 5.0F, -11.0F);
        this.rightarmfin4.setTextureSize(64, 64);
        this.rightarmfin4.mirror = true;
        this.setRotation(this.rightarmfin4, -((float)Math.PI * 2F / 9F), -0.5235988F, 0.0F);
        this.rightarmfin.addChild(this.rightarmfin4);
        this.rightarmfin5 = new ModelRenderer(this, 56, 14);
        this.rightarmfin5.addBox(-0.5F, -1.0F, -5.0F, 1, 3, 1);
        this.rightarmfin5.setRotationPoint(-5.0F, 5.0F, -11.0F);
        this.rightarmfin5.setTextureSize(64, 64);
        this.rightarmfin5.mirror = true;
        this.setRotation(this.rightarmfin5, -((float)Math.PI * 2F / 9F), 0.0F, 0.0F);
        this.rightarmfin.addChild(this.rightarmfin5);
        this.rightarmfin6 = new ModelRenderer(this, 56, 14);
        this.rightarmfin6.addBox(-1.0F, -1.0F, -5.0F, 1, 3, 1);
        this.rightarmfin6.setRotationPoint(-5.0F, 5.0F, -11.0F);
        this.rightarmfin6.setTextureSize(64, 64);
        this.rightarmfin6.mirror = true;
        this.setRotation(this.rightarmfin6, -((float)Math.PI * 2F / 9F), 0.5235988F, 0.0F);
        this.rightarmfin.addChild(this.rightarmfin6);
        this.rightarmfin7 = new ModelRenderer(this, 0, 37);
        this.rightarmfin7.addBox(-1.0F, 0.0F, -5.0F, 1, 1, 5);
        this.rightarmfin7.setRotationPoint(-5.0F, 5.0F, -11.0F);
        this.rightarmfin7.setTextureSize(64, 64);
        this.rightarmfin7.mirror = true;
        this.setRotation(this.rightarmfin7, 0.1745329F, 0.1745329F, 0.0F);
        this.rightarmfin.addChild(this.rightarmfin7);
    }

    public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
    {
        super.render(par1Entity, par2, par3, par4, par5, par6, par7);
        this.setRotationAngles(par1Entity, par2, par3, par4, par5, par6, par7);
        this.head.render(par7);
        this.body.render(par7);
        this.leftlegf.render(par7);
        this.leftlegc.render(par7);
        this.leftlegr.render(par7);
        this.rightlegf.render(par7);
        this.rightlegc.render(par7);
        this.rightlegr.render(par7);
        this.leftarm.render(par7);
        this.rightarm.render(par7);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setLivingAnimations(EntitySpiderPrison par1EntityLiving, float par2, float par3, float par4)
    {
        super.setLivingAnimations(par1EntityLiving, par2, par3, par4);
        int attack = par1EntityLiving.smashCounter / 10;
        this.rightarm.rotateAngleX = (float)attack;
        this.leftarm.rotateAngleX = (float)attack;
    }

    public void setRotationAngles(Entity par1Entity, float f1, float f2, float f3, float f4, float f5, float f6)
    {
        float flag = ((EntitySpiderPrison)par1Entity).getSwingProgressq(f6);
        this.head.rotateAngleY = f4 / (180F / (float)Math.PI);
        this.head.rotateAngleX = f5 / (180F / (float)Math.PI);
        this.leftarm.rotateAngleX = 0.0F;
        this.leftarm.rotateAngleZ = 0.0F;
        this.rightarm.rotateAngleX = 0.0F;
        this.rightarm.rotateAngleZ = 0.0F;

        if (flag > 0.0F)
        {
            this.leftarm.rotateAngleY -= MathHelper.cos(f3 * 0.6F) * 0.05F * 5.0F;
            this.leftarm.rotateAngleZ -= MathHelper.cos(f3 * 0.6F) * 0.05F * 5.0F;
            this.leftarm.rotateAngleX -= MathHelper.sin(f3 * 0.6F) * 0.05F * 18.0F;
            this.rightarm.rotateAngleY = MathHelper.cos(f3 * 0.6F) * 0.05F * 5.0F;
            this.rightarm.rotateAngleZ = MathHelper.cos(f3 * 0.6F) * 0.05F * 5.0F;
            this.rightarm.rotateAngleX -= MathHelper.sin(f3 * 0.6F) * 0.05F * 18.0F;
        }
        else
        {
            this.leftarm.rotateAngleZ -= MathHelper.cos(f3 * 0.09F) * 0.05F + 0.05F;
            this.leftarm.rotateAngleX -= MathHelper.sin(f3 * 0.067F) * 0.05F;
            this.rightarm.rotateAngleZ += MathHelper.cos(f3 * 0.09F) * 0.05F + 0.05F;
            this.rightarm.rotateAngleX += MathHelper.sin(f3 * 0.067F) * 0.05F;
        }

        this.rightarm.rotateAngleY = 0.0F;
        this.leftarm.rotateAngleY = 0.0F;
        float f60 = ((float)Math.PI / 4F);
        this.rightlegr.rotateAngleZ = 0.0F;
        this.leftlegr.rotateAngleZ = 0.0F;
        this.rightlegc.rotateAngleZ = 0.0F;
        this.leftlegc.rotateAngleZ = 0.0F;
        this.rightlegf.rotateAngleZ = 0.0F;
        this.leftlegf.rotateAngleZ = 0.0F;
        float f70 = -0.0F;
        float f80 = 0.3926991F;
        this.rightlegr.rotateAngleY = f80 * 1.0F + f70;
        this.leftlegr.rotateAngleY = -f80 * 1.0F - f70;
        this.rightlegc.rotateAngleY = f80 * 0.0F + f70;
        this.leftlegc.rotateAngleY = -f80 * 0.0F - f70;
        this.rightlegf.rotateAngleY = -f80 * 1.0F + f70;
        this.leftlegf.rotateAngleY = f80 * 1.0F - f70;
        float f9 = -MathHelper.cos(f1 * 0.6662F * 2.0F + 0.0F) * 0.4F * f2;
        float f10 = -MathHelper.cos(f1 * 0.6662F * 2.0F + (float)Math.PI) * 0.4F * f2;
        float f11 = -MathHelper.cos(f1 * 0.6662F * 2.0F + ((float)Math.PI / 2F)) * 0.4F * f2;
        float f12 = -MathHelper.cos(f1 * 0.6662F * 2.0F + ((float)Math.PI * 3F / 2F)) * 0.4F * f2;
        float f13 = Math.abs(MathHelper.sin(f1 * 0.6662F + 0.0F) * 0.4F) * f2;
        float f14 = Math.abs(MathHelper.sin(f1 * 0.6662F + (float)Math.PI) * 0.4F) * f2;
        float f15 = Math.abs(MathHelper.sin(f1 * 0.6662F + ((float)Math.PI / 2F)) * 0.4F) * f2;
        float f16 = Math.abs(MathHelper.sin(f1 * 0.6662F + ((float)Math.PI * 3F / 2F)) * 0.4F) * f2;
        this.rightlegr.rotateAngleY += f9 * 1.5F;
        this.leftlegr.rotateAngleY += -f9 * 1.5F;
        this.rightlegc.rotateAngleY += f10 * 1.5F;
        this.leftlegc.rotateAngleY += -f10 * 1.5F;
        this.rightlegf.rotateAngleY += f12 * 1.5F;
        this.leftlegf.rotateAngleY += -f12 * 1.5F;
        this.rightlegr.rotateAngleZ += f13 * 1.5F;
        this.leftlegr.rotateAngleZ += -f13 * 1.5F;
        this.rightlegc.rotateAngleZ += f14 * 1.5F;
        this.leftlegc.rotateAngleZ += -f14 * 1.5F;
        this.rightlegf.rotateAngleZ += f16 * 1.5F;
        this.leftlegf.rotateAngleZ += -f16 * 1.5F;
    }
}
