package assets;

import net.minecraft.client.addon.tchestplate.armors.models.ModelBaseLavaArmor;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class zzc extends ModelBaseLavaArmor
{
    ModelRenderer Shape1L;
    ModelRenderer Shape2L;
    ModelRenderer Shape3L;
    ModelRenderer Shape4L;
    ModelRenderer Shape5L;
    ModelRenderer Shape6L;
    ModelRenderer Shape7L;
    ModelRenderer Shape8L;
    ModelRenderer Shape9L;
    ModelRenderer Shape10L;
    ModelRenderer Shape11L;
    ModelRenderer Shape12L;
    ModelRenderer Shape13L;
    ModelRenderer Shape14L;
    ModelRenderer Shape15L;
    ModelRenderer Shape16L;
    ModelRenderer Shape17L;
    ModelRenderer Shape18L;
    ModelRenderer Shape19L;
    ModelRenderer Shape20L;
    ModelRenderer Shape21L;
    ModelRenderer Shape22L;
    ModelRenderer Shape23L;
    ModelRenderer Shape24L;
    ModelRenderer Shape1R;
    ModelRenderer Shape2R;
    ModelRenderer Shape3R;
    ModelRenderer Shape4R;
    ModelRenderer Shape5R;
    ModelRenderer Shape6R;
    ModelRenderer Shape7R;
    ModelRenderer Shape8R;
    ModelRenderer Shape9R;
    ModelRenderer Shape10R;
    ModelRenderer Shape11R;
    ModelRenderer Shape12R;
    ModelRenderer Shape13R;
    ModelRenderer Shape14R;
    ModelRenderer Shape15R;
    ModelRenderer Shape16R;
    ModelRenderer Shape17R;
    ModelRenderer Shape18R;
    ModelRenderer Shape19R;
    ModelRenderer Shape20R;
    ModelRenderer Shape21R;
    ModelRenderer Shape22R;
    ModelRenderer Shape23R;
    ModelRenderer Shape24R;

    public zzc()
    {
        textureWidth = 64;
        textureHeight = 64;
        Shape1L = new ModelRenderer(this, 0, 45);
        Shape1L.addBox(0F, 0F, 0F, 4, 2, 4);
        Shape1L.setRotationPoint(-2F, 8F, -1.9F);
        Shape1L.setTextureSize(64, 64);
        Shape1L.mirror = true;
        setRotation(Shape1L, 0F, 0F, 0F);
        Shape2L = new ModelRenderer(this, 46, 45);
        Shape2L.addBox(0F, 0F, 0F, 4, 2, 4);
        Shape2L.setRotationPoint(-2.1F, 8F, -2F);
        Shape2L.setTextureSize(64, 64);
        Shape2L.mirror = true;
        setRotation(Shape2L, 0F, 0F, 0F);
        Shape3L = new ModelRenderer(this, 28, 31);
        Shape3L.addBox(0F, 0F, 0F, 4, 3, 4);
        Shape3L.setRotationPoint(-2F, 0F, -1.9F);
        Shape3L.setTextureSize(64, 64);
        Shape3L.mirror = true;
        setRotation(Shape3L, 0F, 0F, 0F);
        Shape4L = new ModelRenderer(this, 25, 45);
        Shape4L.addBox(0F, 0F, 0F, 4, 3, 4);
        Shape4L.setRotationPoint(-2.1F, 0F, -2F);
        Shape4L.setTextureSize(64, 64);
        Shape4L.mirror = true;
        setRotation(Shape4L, 0F, 0F, 0F);
        Shape5L = new ModelRenderer(this, 35, 52);
        Shape5L.addBox(0F, 0F, 0F, 4, 1, 1);
        Shape5L.setRotationPoint(-2F, 7F, -2.5F);
        Shape5L.setTextureSize(64, 64);
        Shape5L.mirror = true;
        setRotation(Shape5L, 0F, 0F, 0F);
        Shape6L = new ModelRenderer(this, 35, 52);
        Shape6L.addBox(0F, 0F, 0F, 4, 1, 1);
        Shape6L.setRotationPoint(-2F, 7F, 1.5F);
        Shape6L.setTextureSize(64, 64);
        Shape6L.mirror = true;
        setRotation(Shape6L, 0F, 0F, 0F);
        Shape7L = new ModelRenderer(this, 35, 52);
        Shape7L.addBox(0F, 0F, 0F, 1, 1, 5);
        Shape7L.setRotationPoint(1.5F, 7F, -2.5F);
        Shape7L.setTextureSize(64, 64);
        Shape7L.mirror = true;
        setRotation(Shape7L, 0F, 0F, 0F);
        Shape8L = new ModelRenderer(this, 35, 52);
        Shape8L.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape8L.setRotationPoint(1.25F, 6.7F, -1.5F);
        Shape8L.setTextureSize(64, 64);
        Shape8L.mirror = true;
        setRotation(Shape8L, 0F, 0F, 0F);
        Shape9L = new ModelRenderer(this, 35, 52);
        Shape9L.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape9L.setRotationPoint(0.5F, 6.7F, 1.3F);
        Shape9L.setTextureSize(64, 64);
        Shape9L.mirror = true;
        setRotation(Shape9L, 0F, 0F, 0F);
        Shape10L = new ModelRenderer(this, 35, 52);
        Shape10L.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape10L.setRotationPoint(-1.5F, 6.7F, -2.3F);
        Shape10L.setTextureSize(64, 64);
        Shape10L.mirror = true;
        setRotation(Shape10L, 0F, 0F, 0F);
        Shape11L = new ModelRenderer(this, 35, 52);
        Shape11L.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape11L.setRotationPoint(-1.5F, 6.7F, 1.3F);
        Shape11L.setTextureSize(64, 64);
        Shape11L.mirror = true;
        setRotation(Shape11L, 0F, 0F, 0F);
        Shape12L = new ModelRenderer(this, 46, 45);
        Shape12L.addBox(0F, 0F, 0F, 4, 2, 4);
        Shape12L.setRotationPoint(-2F, 8F, -2.1F);
        Shape12L.setTextureSize(64, 64);
        Shape12L.mirror = true;
        setRotation(Shape12L, 0F, 0F, 0F);
        Shape13L = new ModelRenderer(this, 28, 32);
        Shape13L.addBox(0F, 0F, 0F, 4, 3, 4);
        Shape13L.setRotationPoint(-2F, 0F, -2.1F);
        Shape13L.setTextureSize(64, 64);
        Shape13L.mirror = true;
        setRotation(Shape13L, 0F, 0F, 0F);
        Shape14L = new ModelRenderer(this, 28, 37);
        Shape14L.addBox(0F, 0F, 0F, 4, 5, 4);
        Shape14L.setRotationPoint(-2.1F, 3F, -2F);
        Shape14L.setTextureSize(64, 64);
        Shape14L.mirror = true;
        setRotation(Shape14L, 0F, 0F, 0F);
        Shape15L = new ModelRenderer(this, 0, 30);
        Shape15L.addBox(0F, 0F, 0F, 4, 5, 4);
        Shape15L.setRotationPoint(-2F, 3F, -2.1F);
        Shape15L.setTextureSize(64, 64);
        Shape15L.mirror = true;
        setRotation(Shape15L, 0F, 0F, 0F);
        Shape16L = new ModelRenderer(this, 0, 30);
        Shape16L.addBox(0F, 0F, 0F, 4, 5, 4);
        Shape16L.setRotationPoint(-2F, 3F, -1.9F);
        Shape16L.setTextureSize(64, 64);
        Shape16L.mirror = true;
        setRotation(Shape16L, 0F, 0F, 0F);
        Shape17L = new ModelRenderer(this, 35, 52);
        Shape17L.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape17L.setRotationPoint(0.5F, 6.7F, -2.3F);
        Shape17L.setTextureSize(64, 64);
        Shape17L.mirror = true;
        setRotation(Shape17L, 0F, 0F, 0F);
        Shape18L = new ModelRenderer(this, 57, 0);
        Shape18L.addBox(0F, 0F, 0F, 1, 4, 1);
        Shape18L.setRotationPoint(1.3F, 1F, -1F);
        Shape18L.setTextureSize(64, 64);
        Shape18L.mirror = true;
        setRotation(Shape18L, 0F, 0F, 0F);
        Shape19L = new ModelRenderer(this, 57, 0);
        Shape19L.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape19L.setRotationPoint(1.3F, 0F, 0F);
        Shape19L.setTextureSize(64, 64);
        Shape19L.mirror = true;
        setRotation(Shape19L, 0F, 0F, 0F);
        Shape20L = new ModelRenderer(this, 57, 0);
        Shape20L.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape20L.setRotationPoint(-1F, 2F, -2.3F);
        Shape20L.setTextureSize(64, 64);
        Shape20L.mirror = true;
        setRotation(Shape20L, 0F, 0F, 0F);
        Shape21L = new ModelRenderer(this, 57, 0);
        Shape21L.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape21L.setRotationPoint(0F, 1F, -2.3F);
        Shape21L.setTextureSize(64, 64);
        Shape21L.mirror = true;
        setRotation(Shape21L, 0F, 0F, 0F);
        Shape22L = new ModelRenderer(this, 57, 0);
        Shape22L.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape22L.setRotationPoint(-1F, 2F, 1.3F);
        Shape22L.setTextureSize(64, 64);
        Shape22L.mirror = true;
        setRotation(Shape22L, 0F, 0F, 0F);
        Shape23L = new ModelRenderer(this, 57, 0);
        Shape23L.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape23L.setRotationPoint(0F, 1F, 1.3F);
        Shape23L.setTextureSize(64, 64);
        Shape23L.mirror = true;
        setRotation(Shape23L, 0F, 0F, 0F);
        Shape24L = new ModelRenderer(this, 35, 52);
        Shape24L.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape24L.setRotationPoint(1.25F, 6.7F, 0.5F);
        Shape24L.setTextureSize(64, 64);
        Shape24L.mirror = true;
        setRotation(Shape24L, 0F, 0F, 0F);
        Shape1R = new ModelRenderer(this, 35, 52);
        Shape1R.addBox(0F, 0F, 0F, 1, 1, 5);
        Shape1R.setRotationPoint(-2.5F, 7F, -2.5F);
        Shape1R.setTextureSize(64, 64);
        Shape1R.mirror = true;
        setRotation(Shape1R, 0F, 0F, 0F);
        Shape2R = new ModelRenderer(this, 35, 52);
        Shape2R.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape2R.setRotationPoint(-2.3F, 6.7F, 0.5F);
        Shape2R.setTextureSize(64, 64);
        Shape2R.mirror = true;
        setRotation(Shape2R, 0F, 0F, 0F);
        Shape3R = new ModelRenderer(this, 35, 52);
        Shape3R.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape3R.setRotationPoint(0.5F, 6.7F, -2.3F);
        Shape3R.setTextureSize(64, 64);
        Shape3R.mirror = true;
        setRotation(Shape3R, 0F, 0F, 0F);
        Shape4R = new ModelRenderer(this, 35, 52);
        Shape4R.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape4R.setRotationPoint(-2.3F, 6.7F, -1.5F);
        Shape4R.setTextureSize(64, 64);
        Shape4R.mirror = true;
        setRotation(Shape4R, 0F, 0F, 0F);
        Shape5R = new ModelRenderer(this, 57, 0);
        Shape5R.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape5R.setRotationPoint(-1F, 1F, -2.3F);
        Shape5R.setTextureSize(64, 64);
        Shape5R.mirror = true;
        setRotation(Shape5R, 0F, 0F, 0F);
        Shape6R = new ModelRenderer(this, 35, 52);
        Shape6R.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape6R.setRotationPoint(-1.5F, 6.7F, -2.3F);
        Shape6R.setTextureSize(64, 64);
        Shape6R.mirror = true;
        setRotation(Shape6R, 0F, 0F, 0F);
        Shape7R = new ModelRenderer(this, 35, 52);
        Shape7R.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape7R.setRotationPoint(-1.5F, 6.7F, 1.3F);
        Shape7R.setTextureSize(64, 64);
        Shape7R.mirror = true;
        setRotation(Shape7R, 0F, 0F, 0F);
        Shape8R = new ModelRenderer(this, 35, 52);
        Shape8R.addBox(0F, 0F, 0F, 1, 2, 1);
        Shape8R.setRotationPoint(0.5F, 6.7F, 1.3F);
        Shape8R.setTextureSize(64, 64);
        Shape8R.mirror = true;
        setRotation(Shape8R, 0F, 0F, 0F);
        Shape9R = new ModelRenderer(this, 46, 45);
        Shape9R.addBox(0F, 0F, 0F, 4, 2, 4);
        Shape9R.setRotationPoint(-2.1F, 8F, -2F);
        Shape9R.setTextureSize(64, 64);
        Shape9R.mirror = true;
        setRotation(Shape9R, 0F, 0F, 0F);
        Shape10R = new ModelRenderer(this, 36, 34);
        Shape10R.addBox(0F, 0F, 0F, 4, 3, 4);
        Shape10R.setRotationPoint(-2.1F, 0F, -2F);
        Shape10R.setTextureSize(64, 64);
        Shape10R.mirror = true;
        setRotation(Shape10R, 0F, 0F, 0F);
        Shape11R = new ModelRenderer(this, 36, 37);
        Shape11R.addBox(0F, 0F, 0F, 4, 5, 4);
        Shape11R.setRotationPoint(-2.1F, 3F, -2F);
        Shape11R.setTextureSize(64, 64);
        Shape11R.mirror = true;
        setRotation(Shape11R, 0F, 0F, 0F);
        Shape12R = new ModelRenderer(this, 36, 32);
        Shape12R.addBox(0F, 0F, 0F, 4, 3, 4);
        Shape12R.setRotationPoint(-2F, 0F, -2.1F);
        Shape12R.setTextureSize(64, 64);
        Shape12R.mirror = true;
        setRotation(Shape12R, 0F, 0F, 0F);
        Shape13R = new ModelRenderer(this, 20, 32);
        Shape13R.addBox(0F, 0F, 0F, 4, 3, 4);
        Shape13R.setRotationPoint(-2F, 0F, -1.9F);
        Shape13R.setTextureSize(64, 64);
        Shape13R.mirror = true;
        setRotation(Shape13R, 0F, 0F, 0F);
        Shape14R = new ModelRenderer(this, 57, 0);
        Shape14R.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape14R.setRotationPoint(0F, 2F, 1.3F);
        Shape14R.setTextureSize(64, 64);
        Shape14R.mirror = true;
        setRotation(Shape14R, 0F, 0F, 0F);
        Shape15R = new ModelRenderer(this, 57, 0);
        Shape15R.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape15R.setRotationPoint(-2.3F, 0F, 0F);
        Shape15R.setTextureSize(64, 64);
        Shape15R.mirror = true;
        setRotation(Shape15R, 0F, 0F, 0F);
        Shape16R = new ModelRenderer(this, 57, 0);
        Shape16R.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape16R.setRotationPoint(-1F, 1F, 1.3F);
        Shape16R.setTextureSize(64, 64);
        Shape16R.mirror = true;
        setRotation(Shape16R, 0F, 0F, 0F);
        Shape17R = new ModelRenderer(this, 57, 0);
        Shape17R.addBox(0F, 0F, 0F, 1, 3, 1);
        Shape17R.setRotationPoint(0F, 2F, -2.3F);
        Shape17R.setTextureSize(64, 64);
        Shape17R.mirror = true;
        setRotation(Shape17R, 0F, 0F, 0F);
        Shape18R = new ModelRenderer(this, 57, 0);
        Shape18R.addBox(0F, 0F, 0F, 1, 4, 1);
        Shape18R.setRotationPoint(-2.3F, 1F, -1F);
        Shape18R.setTextureSize(64, 64);
        Shape18R.mirror = true;
        setRotation(Shape18R, 0F, 0F, 0F);
        Shape19R = new ModelRenderer(this, 46, 45);
        Shape19R.addBox(0F, 0F, 0F, 4, 2, 4);
        Shape19R.setRotationPoint(-2F, 8F, -2.1F);
        Shape19R.setTextureSize(64, 64);
        Shape19R.mirror = true;
        setRotation(Shape19R, 0F, 0F, 0F);
        Shape20R = new ModelRenderer(this, 0, 45);
        Shape20R.addBox(0F, 0F, 0F, 4, 2, 4);
        Shape20R.setRotationPoint(-2F, 8F, -1.9F);
        Shape20R.setTextureSize(64, 64);
        Shape20R.mirror = true;
        setRotation(Shape20R, 0F, 0F, 0F);
        Shape21R = new ModelRenderer(this, 0, 30);
        Shape21R.addBox(0F, 0F, 0F, 4, 5, 4);
        Shape21R.setRotationPoint(-2F, 3F, -2.1F);
        Shape21R.setTextureSize(64, 64);
        Shape21R.mirror = true;
        setRotation(Shape21R, 0F, 0F, 0F);
        Shape22R = new ModelRenderer(this, 0, 30);
        Shape22R.addBox(0F, 0F, 0F, 4, 5, 4);
        Shape22R.setRotationPoint(-2F, 3F, -1.9F);
        Shape22R.setTextureSize(64, 64);
        Shape22R.mirror = true;
        setRotation(Shape22R, 0F, 0F, 0F);
        Shape23R = new ModelRenderer(this, 35, 52);
        Shape23R.addBox(0F, 0F, 0F, 4, 1, 1);
        Shape23R.setRotationPoint(-2F, 7F, -2.5F);
        Shape23R.setTextureSize(64, 64);
        Shape23R.mirror = true;
        setRotation(Shape23R, 0F, 0F, 0F);
        Shape24R = new ModelRenderer(this, 35, 52);
        Shape24R.addBox(0F, 0F, 0F, 4, 1, 1);
        Shape24R.setRotationPoint(-2F, 7F, 1.5F);
        Shape24R.setTextureSize(64, 64);
        Shape24R.mirror = true;
        setRotation(Shape24R, 0F, 0F, 0F);
        super.bipedRightLeg.cubeList.clear();
        super.bipedRightLeg.addChild(this.Shape1R);
        super.bipedRightLeg.addChild(this.Shape2R);
        super.bipedRightLeg.addChild(this.Shape3R);
        super.bipedRightLeg.addChild(this.Shape4R);
        super.bipedRightLeg.addChild(this.Shape5R);
        super.bipedRightLeg.addChild(this.Shape6R);
        super.bipedRightLeg.addChild(this.Shape7R);
        super.bipedRightLeg.addChild(this.Shape8R);
        super.bipedRightLeg.addChild(this.Shape9R);
        super.bipedRightLeg.addChild(this.Shape10R);
        super.bipedRightLeg.addChild(this.Shape11R);
        super.bipedRightLeg.addChild(this.Shape12R);
        super.bipedRightLeg.addChild(this.Shape13R);
        super.bipedRightLeg.addChild(this.Shape14R);
        super.bipedRightLeg.addChild(this.Shape15R);
        super.bipedRightLeg.addChild(this.Shape16R);
        super.bipedRightLeg.addChild(this.Shape17R);
        super.bipedRightLeg.addChild(this.Shape18R);
        super.bipedRightLeg.addChild(this.Shape19R);
        super.bipedRightLeg.addChild(this.Shape21R);
        super.bipedRightLeg.addChild(this.Shape22R);
        super.bipedRightLeg.addChild(this.Shape23R);
        super.bipedRightLeg.addChild(this.Shape24R);
        super.bipedLeftLeg.cubeList.clear();
        super.bipedLeftLeg.addChild(this.Shape1L);
        super.bipedLeftLeg.addChild(this.Shape2L);
        super.bipedLeftLeg.addChild(this.Shape3L);
        super.bipedLeftLeg.addChild(this.Shape4L);
        super.bipedLeftLeg.addChild(this.Shape5L);
        super.bipedLeftLeg.addChild(this.Shape6L);
        super.bipedLeftLeg.addChild(this.Shape7L);
        super.bipedLeftLeg.addChild(this.Shape8L);
        super.bipedLeftLeg.addChild(this.Shape9L);
        super.bipedLeftLeg.addChild(this.Shape10L);
        super.bipedLeftLeg.addChild(this.Shape11L);
        super.bipedLeftLeg.addChild(this.Shape12L);
        super.bipedLeftLeg.addChild(this.Shape13L);
        super.bipedLeftLeg.addChild(this.Shape14L);
        super.bipedLeftLeg.addChild(this.Shape15L);
        super.bipedLeftLeg.addChild(this.Shape16L);
        super.bipedLeftLeg.addChild(this.Shape17L);
        super.bipedLeftLeg.addChild(this.Shape18L);
        super.bipedLeftLeg.addChild(this.Shape19L);
        super.bipedLeftLeg.addChild(this.Shape20L);
        super.bipedLeftLeg.addChild(this.Shape21L);
        super.bipedLeftLeg.addChild(this.Shape22L);
        super.bipedLeftLeg.addChild(this.Shape23L);
        super.bipedLeftLeg.addChild(this.Shape24L);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

    public String getTexture()
    {
        return "/mods/models/accesories/pantera1.png";
    }
}
