package net.minecraft.client.addon.tchestplate.armors.models;

import net.minecraft.client.addon.tchestplate.armors.models.ModelBaseLavaArmor;
import net.minecraft.client.model.ModelRenderer;

public class ModelOGNBoots
  extends ModelBaseLavaArmor
{
  ModelRenderer ShapeR;
  ModelRenderer ShapeL;
  ModelRenderer ShapeR1;
  ModelRenderer ShapeL1;
  ModelRenderer ShapeR2;
  ModelRenderer ShapeR3;
  ModelRenderer ShapeL3;
  ModelRenderer ShapeL2;
  ModelRenderer ShapeR4;
  ModelRenderer ShapeL4;
  ModelRenderer ShapeR5;
  ModelRenderer ShapeL5;
  ModelRenderer ShapeR6;
  ModelRenderer ShapeL6;
  ModelRenderer ShapeR7;
  ModelRenderer ShapeL7;
  ModelRenderer ShapeR8;
  ModelRenderer ShapeL8;
  ModelRenderer ShapeR9;
  ModelRenderer ShapeL9;
  ModelRenderer ShapeR10;
  ModelRenderer ShapeL10;
  
  public ModelOGNBoots()
  {
    this.textureWidth = 64;
    this.textureHeight = 64;
    this.ShapeR = new ModelRenderer(this, 8, 19);
    this.ShapeR.addBox(-2.5F, 9.2F, -2.5F, 5, 3, 5);
    this.ShapeR.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeR.setTextureSize(64, 64);
    this.ShapeR.mirror = true;
    setRotation(this.ShapeR, 0.0F, 0.0F, 0.0F);
    this.ShapeL = new ModelRenderer(this, 0, 20);
    this.ShapeL.addBox(-2.5F, 9.2F, -2.5F, 5, 3, 5);
    this.ShapeL.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeL.setTextureSize(64, 64);
    this.ShapeL.mirror = true;
    setRotation(this.ShapeL, 0.0F, 0.0F, 0.0F);
    this.ShapeR1 = new ModelRenderer(this, 0, 21);
    this.ShapeR1.addBox(-2.0F, 9.0F, -3.0F, 4, 3, 1);
    this.ShapeR1.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeR1.setTextureSize(64, 64);
    this.ShapeR1.mirror = true;
    setRotation(this.ShapeR1, 0.0F, 0.0F, 0.0F);
    this.ShapeL1 = new ModelRenderer(this, 0, 20);
    this.ShapeL1.addBox(-2.0F, 9.0F, -3.0F, 4, 3, 1);
    this.ShapeL1.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeL1.setTextureSize(64, 64);
    this.ShapeL1.mirror = true;
    setRotation(this.ShapeL1, 0.0F, 0.0F, 0.0F);
    this.ShapeR2 = new ModelRenderer(this, 0, 18);
    this.ShapeR2.addBox(2.0F, 9.0F, -1.0F, 1, 1, 3);
    this.ShapeR2.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeR2.setTextureSize(64, 64);
    this.ShapeR2.mirror = true;
    setRotation(this.ShapeR2, 0.0F, 0.0F, 0.0F);
    this.ShapeR3 = new ModelRenderer(this, 0, 17);
    this.ShapeR3.addBox(2.0F, 8.0F, 0.0F, 1, 1, 2);
    this.ShapeR3.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeR3.setTextureSize(64, 64);
    this.ShapeR3.mirror = true;
    setRotation(this.ShapeR3, 0.0F, 0.0F, 0.0F);
    this.ShapeL3 = new ModelRenderer(this, 0, 17);
    this.ShapeL3.addBox(-3.0F, 8.0F, 0.0F, 1, 1, 2);
    this.ShapeL3.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeL3.setTextureSize(64, 64);
    this.ShapeL3.mirror = true;
    setRotation(this.ShapeL3, 0.0F, 0.0F, 0.0F);
    this.ShapeL2 = new ModelRenderer(this, 0, 18);
    this.ShapeL2.addBox(-3.0F, 9.0F, -1.0F, 1, 1, 3);
    this.ShapeL2.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeL2.setTextureSize(64, 64);
    this.ShapeL2.mirror = true;
    setRotation(this.ShapeL2, 0.0F, 0.0F, 0.0F);
    this.ShapeR4 = new ModelRenderer(this, 0, 20);
    this.ShapeR4.addBox(-2.0F, 10.0F, -4.0F, 4, 2, 1);
    this.ShapeR4.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeR4.setTextureSize(64, 64);
    this.ShapeR4.mirror = true;
    setRotation(this.ShapeR4, 0.0F, 0.0F, 0.0F);
    this.ShapeL4 = new ModelRenderer(this, 0, 20);
    this.ShapeL4.addBox(-2.0F, 10.0F, -4.0F, 4, 2, 1);
    this.ShapeL4.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeL4.setTextureSize(64, 64);
    this.ShapeL4.mirror = true;
    setRotation(this.ShapeL4, 0.0F, 0.0F, 0.0F);
    this.ShapeR5 = new ModelRenderer(this, 0, 17);
    this.ShapeR5.addBox(-0.5F, 9.0F, -4.0F, 1, 1, 1);
    this.ShapeR5.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeR5.setTextureSize(64, 64);
    this.ShapeR5.mirror = true;
    setRotation(this.ShapeR5, 0.0F, 0.0F, 0.0F);
    this.ShapeL5 = new ModelRenderer(this, 0, 18);
    this.ShapeL5.addBox(-0.5F, 9.0F, -4.0F, 1, 1, 1);
    this.ShapeL5.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeL5.setTextureSize(64, 64);
    this.ShapeL5.mirror = true;
    setRotation(this.ShapeL5, 0.0F, 0.0F, 0.0F);
    this.ShapeR6 = new ModelRenderer(this, 0, 21);
    this.ShapeR6.addBox(-1.0F, 8.0F, -3.0F, 2, 1, 1);
    this.ShapeR6.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeR6.setTextureSize(64, 64);
    this.ShapeR6.mirror = true;
    setRotation(this.ShapeR6, 0.0F, 0.0F, 0.0F);
    this.ShapeL6 = new ModelRenderer(this, 0, 20);
    this.ShapeL6.addBox(-1.0F, 8.0F, -3.0F, 2, 1, 1);
    this.ShapeL6.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeL6.setTextureSize(64, 64);
    this.ShapeL6.mirror = true;
    setRotation(this.ShapeL6, 0.0F, 0.0F, 0.0F);
    this.ShapeR7 = new ModelRenderer(this, 0, 20);
    this.ShapeR7.addBox(-1.0F, 10.0F, -5.0F, 2, 1, 1);
    this.ShapeR7.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeR7.setTextureSize(64, 64);
    this.ShapeR7.mirror = true;
    setRotation(this.ShapeR7, 0.0F, 0.0F, 0.0F);
    this.ShapeL7 = new ModelRenderer(this, 0, 17);
    this.ShapeL7.addBox(-1.0F, 10.0F, -5.0F, 2, 1, 1);
    this.ShapeL7.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeL7.setTextureSize(64, 64);
    this.ShapeL7.mirror = true;
    setRotation(this.ShapeL7, 0.0F, 0.0F, 0.0F);
    this.ShapeR8 = new ModelRenderer(this, 0, 19);
    this.ShapeR8.addBox(-1.5F, 11.0F, -5.0F, 3, 1, 1);
    this.ShapeR8.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeR8.setTextureSize(64, 64);
    this.ShapeR8.mirror = true;
    setRotation(this.ShapeR8, 0.0F, 0.0F, 0.0F);
    this.ShapeL8 = new ModelRenderer(this, 0, 19);
    this.ShapeL8.addBox(-1.5F, 11.0F, -5.0F, 3, 1, 1);
    this.ShapeL8.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeL8.setTextureSize(64, 64);
    this.ShapeL8.mirror = true;
    setRotation(this.ShapeL8, 0.0F, 0.0F, 0.0F);
    this.ShapeR9 = new ModelRenderer(this, 0, 17);
    this.ShapeR9.addBox(-1.5F, 9.0F, 2.0F, 3, 1, 1);
    this.ShapeR9.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeR9.setTextureSize(64, 64);
    this.ShapeR9.mirror = true;
    setRotation(this.ShapeR9, 0.0F, 0.0F, 0.0F);
    this.ShapeL9 = new ModelRenderer(this, 0, 17);
    this.ShapeL9.addBox(-1.5F, 9.0F, 2.0F, 3, 1, 1);
    this.ShapeL9.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeL9.setTextureSize(64, 64);
    this.ShapeL9.mirror = true;
    setRotation(this.ShapeL9, 0.0F, 0.0F, 0.0F);
    this.ShapeR10 = new ModelRenderer(this, 0, 21);
    this.ShapeR10.addBox(-0.5F, 8.0F, 2.0F, 1, 1, 1);
    this.ShapeR10.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeR10.setTextureSize(64, 64);
    this.ShapeR10.mirror = true;
    setRotation(this.ShapeR10, 0.0F, 0.0F, 0.0F);
    this.ShapeL10 = new ModelRenderer(this, 0, 21);
    this.ShapeL10.addBox(-0.5F, 8.0F, 2.0F, 1, 1, 1);
    this.ShapeL10.setRotationPoint(0.0F, 0.0F, 0.0F);
    this.ShapeL10.setTextureSize(64, 64);
    this.ShapeL10.mirror = true;
    setRotation(this.ShapeL10, 0.0F, 0.0F, 0.0F);
    
    this.bipedRightLeg.cubeList.clear();
    this.bipedRightLeg.addChild(this.ShapeL);
    this.bipedRightLeg.addChild(this.ShapeL1);
    this.bipedRightLeg.addChild(this.ShapeL2);
    this.bipedRightLeg.addChild(this.ShapeL3);
    this.bipedRightLeg.addChild(this.ShapeL4);
    this.bipedRightLeg.addChild(this.ShapeL5);
    this.bipedRightLeg.addChild(this.ShapeL6);
    this.bipedRightLeg.addChild(this.ShapeL7);
    this.bipedRightLeg.addChild(this.ShapeL8);
    this.bipedRightLeg.addChild(this.ShapeL9);
    this.bipedRightLeg.addChild(this.ShapeL10);
    this.bipedLeftLeg.cubeList.clear();
    this.bipedLeftLeg.addChild(this.ShapeR);
    this.bipedLeftLeg.addChild(this.ShapeR1);
    this.bipedLeftLeg.addChild(this.ShapeR2);
    this.bipedLeftLeg.addChild(this.ShapeR3);
    this.bipedLeftLeg.addChild(this.ShapeR4);
    this.bipedLeftLeg.addChild(this.ShapeR5);
    this.bipedLeftLeg.addChild(this.ShapeR6);
    this.bipedLeftLeg.addChild(this.ShapeR7);
    this.bipedLeftLeg.addChild(this.ShapeR8);
    this.bipedLeftLeg.addChild(this.ShapeR9);
    this.bipedLeftLeg.addChild(this.ShapeR10);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
